import type { LevelConfig } from '../engine';

export const aurora: LevelConfig = {
  id: 'aurora',
  order: 3,
  title: 'Aurora',
  backgroundPlate: 'assets/production/backgrounds/bg-03-aurora.png',
  laneTint: '#6fb8ad',
  particleConfig: {
    snowDensity: 0.18,
    mistOpacity: 0.24,
    breathRingOnLanding: true,
    auroraIntensity: 0.52,
  },
  ambientAudioPath: 'assets/production/audio/ambient-03-aurora.mp3',
  runnerSpeed: 315,
  tempo: 1,
  forwardSpeed: 1.02,
  audioToSpawnDelay: 1500,
  cardTravelDuration: 4550,
  postWaveDelay: 1420,
  audioToTileMs: 6050,
  timingWindowMs: 800,
  distractorCount: 2,
  bluffFrequency: 0,
  decisionDistance: 0.8,
  biome: {
    name: 'Aurora',
    sky: ['#071016', '#123642', '#6fb8ad'],
    horizon: '#6fb8ad',
    lane: '#7faad4',
    cardGlow: '#b8fff2',
    particle: 'aurora',
    ambient: { root: 196, color: '#6fb8ad', cutoff: 920 },
    parallax: ['ribbon lights', 'ice-black ridges', 'distant moon wash'],
  },
  mechanics: { variableLaneWidth: true },
};
