import type { LevelConfig } from '../engine';

export const embers: LevelConfig = {
  id: 'embers',
  order: 7,
  title: 'Embers',
  backgroundPlate: 'assets/production/backgrounds/bg-07-embers.png',
  laneTint: '#a8d8ea',
  particleConfig: {
    snowDensity: 0.1,
    mistOpacity: 0.18,
    breathRingOnLanding: true,
    crystalDensity: 0.2,
  },
  ambientAudioPath: 'assets/production/audio/ambient-07-embers.mp3',
  runnerSpeed: 390,
  tempo: 1.22,
  forwardSpeed: 1.38,
  audioToSpawnDelay: 1500,
  cardTravelDuration: 3650,
  postWaveDelay: 1260,
  audioToTileMs: 5150,
  timingWindowMs: 620,
  distractorCount: 2,
  bluffFrequency: 0.22,
  decisionDistance: 0.74,
  biome: {
    name: 'Embers',
    sky: ['#050505', '#1a0a00', '#a54216'],
    horizon: '#ff8a3d',
    lane: '#ff6b35',
    cardGlow: '#ffd700',
    particle: 'embers',
    ambient: { root: 110, color: '#ff8a3d', cutoff: 620 },
    parallax: ['banked fire glow', 'rising ash', 'charcoal plinths'],
  },
  mechanics: {},
};
