import type { LevelConfig } from '../engine';

export const reverie: LevelConfig = {
  id: 'reverie',
  order: 10,
  title: 'Reverie',
  backgroundPlate: 'assets/production/backgrounds/bg-10-reverie.png',
  laneTint: '#d0f0ff',
  particleConfig: {
    snowDensity: 0.22,
    mistOpacity: 0.48,
    breathRingOnLanding: true,
    rainDensity: 0.18,
    auroraIntensity: 0.22,
    crystalDensity: 0.26,
  },
  ambientAudioPath: 'assets/production/audio/ambient-10-reverie.mp3',
  runnerSpeed: 455,
  tempo: 1.36,
  forwardSpeed: 1.62,
  audioToSpawnDelay: 1500,
  cardTravelDuration: 3000,
  postWaveDelay: 1150,
  audioToTileMs: 4500,
  timingWindowMs: 520,
  distractorCount: 2,
  bluffFrequency: 0.3,
  decisionDistance: 0.68,
  biome: {
    name: 'Reverie',
    sky: ['#07090a', '#172333', '#d3b77b'],
    horizon: '#edf5f8',
    lane: '#7faad4',
    cardGlow: '#f8f1d9',
    particle: 'dream',
    ambient: { root: 185, color: '#edf5f8', cutoff: 1120 },
    parallax: ['mixed biome echoes', 'impossible steps', 'soft inverted horizon'],
  },
  mechanics: {
    variableLaneWidth: true,
    tileRotation: true,
    fogBursts: true,
    doublePrompts: true,
    rotatingMechanics: true,
  },
};
