import type { LevelConfig } from '../engine';

export const tideline: LevelConfig = {
  id: 'tideline',
  order: 5,
  title: 'Tideline',
  backgroundPlate: 'assets/production/backgrounds/bg-05-tideline.png',
  laneTint: '#a8d8ea',
  particleConfig: {
    snowDensity: 0.18,
    mistOpacity: 0.34,
    breathRingOnLanding: true,
  },
  ambientAudioPath: 'assets/production/audio/ambient-05-tideline.mp3',
  runnerSpeed: 340,
  tempo: 1.06,
  forwardSpeed: 1.12,
  audioToSpawnDelay: 1500,
  cardTravelDuration: 4100,
  postWaveDelay: 1340,
  audioToTileMs: 5600,
  timingWindowMs: 720,
  distractorCount: 2,
  bluffFrequency: 0.18,
  decisionDistance: 0.78,
  biome: {
    name: 'Tideline',
    sky: ['#071a21', '#12455a', '#8ab6c8'],
    horizon: '#7da9b8',
    lane: '#3f7375',
    cardGlow: '#c9f0f5',
    particle: 'foam',
    ambient: { root: 174.61, color: '#7da9b8', cutoff: 820 },
    parallax: ['foam sheets', 'half-sunken columns', 'pale gull-less sky'],
  },
  mechanics: {},
};
