-- Follow-up to 20260421000000_pipeline_events.sql.
--
-- The original migration created pipeline_events with four FKs defaulting to
-- ON DELETE NO ACTION. That turns every audit row into a block on legitimate
-- user-data deletion (GDPR request, test-data wipe, admin cleanup of a deck).
--
-- Switch each FK to ON DELETE SET NULL so audit rows survive as append-only
-- facts with NULL identity once the referent is gone — matching the
-- "Rows are immutable facts" contract in the original migration header while
-- not holding user data deletion hostage to the audit trail.
--
-- Constraint names are the Postgres defaults generated by the inline
-- `uuid references ...` declarations in the original migration
-- ({table}_{column}_fkey).

BEGIN;

ALTER TABLE public.pipeline_events
  DROP CONSTRAINT pipeline_events_word_id_fkey,
  ADD CONSTRAINT pipeline_events_word_id_fkey
    FOREIGN KEY (word_id) REFERENCES public.words(id) ON DELETE SET NULL;

ALTER TABLE public.pipeline_events
  DROP CONSTRAINT pipeline_events_deck_id_fkey,
  ADD CONSTRAINT pipeline_events_deck_id_fkey
    FOREIGN KEY (deck_id) REFERENCES public.decks(id) ON DELETE SET NULL;

ALTER TABLE public.pipeline_events
  DROP CONSTRAINT pipeline_events_user_id_fkey,
  ADD CONSTRAINT pipeline_events_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.pipeline_events
  DROP CONSTRAINT pipeline_events_job_id_fkey,
  ADD CONSTRAINT pipeline_events_job_id_fkey
    FOREIGN KEY (job_id) REFERENCES public.generation_jobs(id) ON DELETE SET NULL;

COMMIT;

-- Rollback:
-- BEGIN;
--   ALTER TABLE public.pipeline_events
--     DROP CONSTRAINT pipeline_events_word_id_fkey,
--     ADD CONSTRAINT pipeline_events_word_id_fkey
--       FOREIGN KEY (word_id) REFERENCES public.words(id);
--   ALTER TABLE public.pipeline_events
--     DROP CONSTRAINT pipeline_events_deck_id_fkey,
--     ADD CONSTRAINT pipeline_events_deck_id_fkey
--       FOREIGN KEY (deck_id) REFERENCES public.decks(id);
--   ALTER TABLE public.pipeline_events
--     DROP CONSTRAINT pipeline_events_user_id_fkey,
--     ADD CONSTRAINT pipeline_events_user_id_fkey
--       FOREIGN KEY (user_id) REFERENCES public.profiles(id);
--   ALTER TABLE public.pipeline_events
--     DROP CONSTRAINT pipeline_events_job_id_fkey,
--     ADD CONSTRAINT pipeline_events_job_id_fkey
--       FOREIGN KEY (job_id) REFERENCES public.generation_jobs(id);
-- COMMIT;
