import { useMemo } from 'react'
import { collectSceneStills } from '@/lib/sceneStills'
import type { PipelineEvent } from '@/lib/observability'
import styles from './observability.module.css'

export default function SceneStills({ events }: { events: PipelineEvent[] }) {
  const stills = useMemo(() => collectSceneStills(events), [events])

  if (stills.length === 0) return null

  return (
    <section className={styles.sceneStills}>
      <div className={styles.sceneStillsHeader}>
        <span className={styles.bodyLabel}>Rendered scene stills</span>
        <span className={styles.sceneStillsCount}>{stills.length} scene records</span>
      </div>
      <div className={styles.sceneStillGrid}>
        {stills.map((still) => (
          <article key={`${still.eventId}-${still.provider}`} className={styles.sceneStillCard}>
            <div className={styles.sceneStillMeta}>
              <span>Scene {String(still.sceneNumber).padStart(3, '0')}</span>
              <span>{still.provider}</span>
            </div>
            {still.available && still.url ? (
              <a
                href={still.url}
                target="_blank"
                rel="noreferrer"
                className={styles.sceneStillLink}
                aria-label={`Open full resolution still for scene ${still.sceneNumber} from ${still.provider}`}
              >
                <img
                  className={styles.sceneStillImage}
                  src={still.url}
                  alt={`Scene ${still.sceneNumber} still generated by ${still.provider}`}
                  loading="lazy"
                  onError={(event) => {
                    event.currentTarget.style.display = 'none'
                    const fallback = event.currentTarget
                      .closest(`.${styles.sceneStillCard}`)
                      ?.querySelector<HTMLElement>(`.${styles.sceneStillMissing}`)
                    if (fallback) fallback.hidden = false
                  }}
                />
              </a>
            ) : null}
            <div className={styles.sceneStillMissing} hidden={still.available}>
              Still not available
            </div>
          </article>
        ))}
      </div>
    </section>
  )
}
