/**
 * Script Lab audio batch — generates one MP3 per declared ScriptAudioSpec via
 * ElevenLabs into public/scripts/<scriptId>/<itemId>.mp3, then rewrites
 * src/lib/scriptlab/audioManifest.generated.ts from what actually exists on
 * disk. lib/scriptlab/audio.ts serves manifest assets first and only falls
 * back to browser speechSynthesis for items without a file.
 *
 * Run from frontend/:
 *   ELEVENLABS_API_KEY=... npx tsx scripts/generate-script-lab-audio.ts [--dry-run]
 *
 * Idempotent: existing MP3s are kept (delete a file to force regeneration).
 * Only scripts listed in VOICE_BY_SCRIPT are processed — add an entry when a
 * new writing system gets its audio batch approved.
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { SCRIPTS } from '../src/lib/scriptlab/registry.ts'
import type { ScriptAudioSpec } from '../src/lib/scriptlab/types.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PUBLIC_DIR = path.join(__dirname, '../public/scripts')
const MANIFEST_FILE = path.join(__dirname, '../src/lib/scriptlab/audioManifest.generated.ts')

const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY
const ELEVENLABS_API_URL = 'https://api.elevenlabs.io/v1/text-to-speech'
const ELEVENLABS_MODEL = 'eleven_multilingual_v2'
const DRY_RUN = process.argv.includes('--dry-run')

/** Voice per script. Korean: Jini — one of the six QA'd ko voices from the
 * static thematic TTS batches (ElevenLabs id from scripts/generate-voices.ts). */
const VOICE_BY_SCRIPT: Record<string, { voiceName: string; elevenLabsId: string }> = {
  'korean-hangul': { voiceName: 'Jini', elevenLabsId: '0oqpliV6dVSr9XomngOW' },
}

// Single letters/syllables need a stable, unstylized read.
const VOICE_SETTINGS = {
  stability: 0.6,
  similarity_boost: 0.75,
  style: 0.15,
  use_speaker_boost: true,
}

function collectSpecs(symbols: Array<{
  audio: ScriptAudioSpec
  exampleSyllableAudio?: ScriptAudioSpec
  exampleWord: { audio: ScriptAudioSpec }
}>): ScriptAudioSpec[] {
  const byId = new Map<string, ScriptAudioSpec>()
  for (const symbol of symbols) {
    for (const spec of [symbol.audio, symbol.exampleSyllableAudio, symbol.exampleWord.audio]) {
      if (!spec) continue
      const existing = byId.get(spec.itemId)
      if (existing && existing.text !== spec.text) {
        throw new Error(`itemId ${spec.itemId} declared with two different texts`)
      }
      byId.set(spec.itemId, spec)
    }
  }
  return [...byId.values()]
}

async function synthesize(voiceId: string, text: string, filepath: string): Promise<boolean> {
  const response = await fetch(`${ELEVENLABS_API_URL}/${voiceId}`, {
    method: 'POST',
    headers: { 'xi-api-key': ELEVENLABS_API_KEY!, 'Content-Type': 'application/json' },
    body: JSON.stringify({ text, model_id: ELEVENLABS_MODEL, voice_settings: VOICE_SETTINGS }),
  })
  if (!response.ok) {
    console.error(`  FAIL ${path.basename(filepath)}: ${response.status} ${await response.text()}`)
    return false
  }
  const audio = Buffer.from(await response.arrayBuffer())
  if (audio.length < 1024) {
    console.error(`  FAIL ${path.basename(filepath)}: suspiciously small payload (${audio.length} B)`)
    return false
  }
  fs.writeFileSync(filepath, audio)
  return true
}

function writeManifest(processedScriptIds: string[]) {
  const manifest: Record<string, Record<string, string>> = {}
  for (const scriptId of processedScriptIds) {
    const dir = path.join(PUBLIC_DIR, scriptId)
    if (!fs.existsSync(dir)) continue
    const entries: Record<string, string> = {}
    for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.mp3')).sort()) {
      entries[file.replace(/\.mp3$/, '')] = `/scripts/${scriptId}/${file}`
    }
    if (Object.keys(entries).length > 0) manifest[scriptId] = entries
  }
  const body = [
    '// AUTO-GENERATED by scripts/generate-script-lab-audio.ts — do not edit by hand.',
    '// Maps scriptId → audio itemId → static asset path under public/.',
    '',
    `export const GENERATED_SCRIPT_AUDIO: Record<string, Record<string, string>> = ${JSON.stringify(manifest, null, 2)}`,
    '',
  ].join('\n')
  fs.writeFileSync(MANIFEST_FILE, body)
  console.log(`\nManifest written: ${path.relative(process.cwd(), MANIFEST_FILE)}`)
}

async function main() {
  const targets = SCRIPTS.filter((entry) => VOICE_BY_SCRIPT[entry.id])
  if (targets.length === 0) {
    console.error('No registered script has a voice configured in VOICE_BY_SCRIPT.')
    process.exit(1)
  }

  let failures = 0
  for (const entry of targets) {
    const { default: script } = await entry.load()
    const specs = collectSpecs(script.symbols)
    const totalChars = specs.reduce((sum, spec) => sum + spec.text.length, 0)
    const voice = VOICE_BY_SCRIPT[entry.id]
    console.log(`\n${entry.id}: ${specs.length} items, ${totalChars} chars total, voice ${voice.voiceName}`)

    const badId = specs.find((spec) => !/^[a-z0-9-]+$/.test(spec.itemId))
    if (badId) throw new Error(`itemId not filename-safe: ${badId.itemId}`)

    if (DRY_RUN) {
      for (const spec of specs) console.log(`  ${spec.itemId} ← "${spec.text}"`)
      continue
    }
    if (!ELEVENLABS_API_KEY) {
      console.error('ELEVENLABS_API_KEY is not set')
      process.exit(1)
    }

    const dir = path.join(PUBLIC_DIR, entry.id)
    fs.mkdirSync(dir, { recursive: true })

    for (const spec of specs) {
      const filepath = path.join(dir, `${spec.itemId}.mp3`)
      if (fs.existsSync(filepath)) continue
      process.stdout.write(`  ${spec.itemId} ("${spec.text}") ... `)
      const ok = await synthesize(voice.elevenLabsId, spec.text, filepath)
      if (ok) console.log(`${(fs.statSync(filepath).size / 1024).toFixed(1)} KB`)
      else failures += 1
      await new Promise((resolve) => setTimeout(resolve, 300))
    }
  }

  if (!DRY_RUN) writeManifest(targets.map((entry) => entry.id))
  if (failures > 0) {
    console.error(`\n${failures} item(s) failed — rerun to retry just those.`)
    process.exit(1)
  }
  console.log('\nAll audio assets present.')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
