import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { CHARACTER_REGISTRY } from '../src/characterRegistry'
import { GEMINI_CHARACTER_MODES } from '../src/data/geminiCharacterModes'

// Vercel compiles api/ as CommonJS and src/ as ESM. Project only the text
// policy into api/ so no runtime require crosses that package boundary.
const characters = CHARACTER_REGISTRY.map(({ id, name, tier, identity, directive }) => ({ id, name, tier, identity, directive }))
const modes = GEMINI_CHARACTER_MODES.map(({ id, geminiVibeFlavor, geminiVibeHint, geminiVibeDirective }) => ({ id, geminiVibeFlavor, geminiVibeHint, geminiVibeDirective }))
const output = '// Generated by npm run generate:speak-personas. Edit the source registries, then regenerate.\n'
  + `export const CHARACTER_REGISTRY = ${JSON.stringify(characters, null, 2)} as const\n\n`
  + `export const GEMINI_CHARACTER_MODES = ${JSON.stringify(modes, null, 2)} as const\n`
const outputPath = resolve('api/_shared/speakPersonaCatalog.ts')
if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8').replaceAll('\r\n', '\n') !== output) {
    throw new Error('Speak persona catalog is stale. Run npm run generate:speak-personas.')
  }
  console.log('Speak API catalog matches the source registries')
} else {
  writeFileSync(outputPath, output)
  console.log('Generated Speak API catalog')
}
