import { generateGeminiTtsFromPrompt } from './_shared/geminiTts'

// Vercel Serverless Function — Voice Tutor pipeline
// POST /api/voice-chat
// Body: { audio_base64: string|null, language: string, history: Message[], mime_type?: string }
// Returns: { user_text, ai_text, audio_base64, audio_format }
//
// Verified Gemini TTS response shape (live smoke test 2026-04-17 vs
// gemini-3.1-flash-tts-preview, mode=calm, voice=Aoede, en-intro sentence):
//   {
//     candidates: [{ content: { parts: [{ inlineData: {
//       mimeType: "audio/l16; rate=24000; channels=1",
//       data: "<base64 PCM16 mono 24kHz>"
//     } }] } }],
//     usageMetadata: { promptTokenCount, candidatesTokenCount, totalTokenCount, ... },
//     modelVersion, responseId
//   }
// PCM length for the 24-word intro sentence: 643,200 bytes (~13.4s audio).
// Wrap with wrapPcmAsWav() before returning to the client.

interface Message {
  role: 'user' | 'assistant' | 'system'
  content: string
}

interface RequestBody {
  audio_base64: string | null
  language: string
  history: Message[]
  voice_id?: string
  elevenlabs_voice_id?: string
  mime_type?: string
  level?: string
  native_language?: string
  character_name?: string
  character_tier?: 'style' | 'persona' | 'public'
  character_identity?: string
  character_directive?: string
  study_words?: Array<{ word: string; translation: string }>
  mode?: 'corrections' | 'roleplay'
  scenarioPrompt?: string
  provider?: 'voxtral' | 'gemini'
  gemini_character_mode_id?: string
  gemini_voice_name?: string
  gemini_accent_id?: string
}

interface CharacterPayload {
  name: string
  tier: 'style' | 'persona' | 'public'
  identity?: string
  directive: string
}

const LANGUAGE_CONFIG: Record<string, { name: string; nativeName: string; encouragement: string; fillers: string }> = {
  en: { name: 'English', nativeName: 'English', encouragement: 'Great job! / Well done! / That\'s right!', fillers: 'Well, So, You know, Actually' },
  de: { name: 'German', nativeName: 'Deutsch', encouragement: 'Sehr gut! / Prima! / Genau!', fillers: 'Also, Na ja, Weißt du, Eigentlich' },
  fr: { name: 'French', nativeName: 'Français', encouragement: 'Très bien! / Bravo! / C\'est parfait!', fillers: 'Alors, Bon, Tu sais, En fait' },
  it: { name: 'Italian', nativeName: 'Italiano', encouragement: 'Molto bene! / Bravissimo! / Perfetto!', fillers: 'Allora, Dunque, Sai, In realtà' },
  es: { name: 'Spanish', nativeName: 'Español', encouragement: '¡Muy bien! / ¡Excelente! / ¡Perfecto!', fillers: 'Bueno, Pues, Sabes, En realidad' },
  pt: { name: 'Portuguese', nativeName: 'Português', encouragement: 'Muito bem! / Ótimo! / Perfeito!', fillers: 'Então, Bom, Sabes, Na verdade' },
  nl: { name: 'Dutch', nativeName: 'Nederlands', encouragement: 'Heel goed! / Prima! / Uitstekend!', fillers: 'Nou, Dus, Weet je, Eigenlijk' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', encouragement: 'बहुत अच्छा! / शाबाश! / बिल्कुल सही!', fillers: 'तो, अच्छा, देखो, वैसे' },
  ar:  { name: 'Arabic',    nativeName: 'العربية',          encouragement: '!أحسنت / !ممتاز / !رائع',             fillers: 'يعني / طيب / فعلاً' },
  fil: { name: 'Filipino',  nativeName: 'Filipino',         encouragement: 'Magaling! / Napakahusay! / Tama!',     fillers: 'Kaya, So, Alam mo, Talaga' },
  id:  { name: 'Indonesian', nativeName: 'Bahasa Indonesia', encouragement: 'Bagus sekali! / Hebat! / Benar!',      fillers: 'Jadi, Nah, Tau nggak, Sebenarnya' },
  ko:  { name: 'Korean',    nativeName: '한국어',            encouragement: '잘했어요! / 훌륭해요! / 맞아요!',        fillers: '음, 그러니까, 있잖아, 사실은' },
}

// Native language names for browser language codes not in LANGUAGE_CONFIG
const NATIVE_LANGUAGE_NAMES: Record<string, string> = {
  en: 'English', de: 'German', fr: 'French', it: 'Italian',
  es: 'Spanish', pt: 'Portuguese', nl: 'Dutch', hi: 'Hindi',
  ar: 'Arabic', fil: 'Filipino', id: 'Indonesian', ko: 'Korean',
  zh: 'Chinese', ja: 'Japanese', ru: 'Russian', tr: 'Turkish',
  pl: 'Polish', th: 'Thai', vi: 'Vietnamese', sv: 'Swedish',
  da: 'Danish', no: 'Norwegian', fi: 'Finnish', cs: 'Czech',
  uk: 'Ukrainian', ro: 'Romanian', hu: 'Hungarian', el: 'Greek',
  he: 'Hebrew', ms: 'Malay', tl: 'Tagalog',
}

// Mistral custom voice IDs — generated by scripts/generate-voices.ts
// Placeholder 'xxx' means: run the script, then paste actual voice_ids here.
// Until populated, falls back to preset voices (en_paul_cheerful / en_paul_confident).
const VOICE_MAP: Record<string, { voiceId: string; name: string; gender: string }> = {
  en: { voiceId: 'b20117b6-f11c-461f-9978-19968c237e32', name: 'Hope',     gender: 'female' },
  de: { voiceId: '5eea3a34-f977-4bbc-9a67-4050588ebc83', name: 'Mila',     gender: 'female' },
  fr: { voiceId: '99104b5b-e943-4598-878d-0a881a45baef', name: 'Claire',   gender: 'female' },
  it: { voiceId: '38647032-b1b5-4f8e-8ef6-04ac11925296', name: 'Elettra',  gender: 'female' },
  es: { voiceId: '20c4028f-ec23-47ae-af8a-fb2e0615abd8', name: 'Carolina', gender: 'female' },
  pt: { voiceId: '80d1df25-564a-47b6-9325-bb61277c8464', name: 'Yasmin',   gender: 'female' },
  nl: { voiceId: 'b6ed2ec1-bace-4d5e-88c2-ee1d881c115d', name: 'Melanie',  gender: 'female' },
  hi: { voiceId: '8dfc9345-ba80-4f88-91e8-92205ca53807', name: 'Kanika',   gender: 'female' },
  ar: { voiceId: '414a56c0-f4de-4ec1-8f8a-2bfffe963a1c', name: 'Yousef',   gender: 'male'   },
}

// Languages supported by Voxtral TTS (others fall back to ElevenLabs)
const VOXTRAL_SUPPORTED = new Set(['en', 'de', 'fr', 'it', 'es', 'pt', 'nl', 'hi', 'ar'])

// ElevenLabs voice IDs for languages Voxtral cannot speak
const ELEVENLABS_FALLBACK: Record<string, string> = {
  fil: '4RLeKvASM0Zt73Htf5GF', // Maria
  id:  '52LXmmR0nGnIcDs1TL3f', // Anjani
  ko:  'zgDzx5jLLCqEp6Fl7Kl7', // Hanna
}

// ⚠️ KEEP IN SYNC with src/data/geminiCharacterModes.ts
// If you edit a geminiStylePrompt, bump the `version` field here AND in the
// src/ twin, and UPDATE voice_samples SET invalidated_at = now() for that
// character_mode_id so cached samples regenerate.
const GEMINI_CHARACTER_MODES: ReadonlyArray<{
  id: string
  name: string
  description: string
  geminiStylePrompt: string
  version: number
}> = [
  {
    id: 'calm',
    name: 'Calm',
    description: 'Patient, slow-paced, encouraging meditation teacher',
    geminiStylePrompt: `Warm, slow, soft-volume meditation teacher. Lower pitch, softened consonants, generous pauses. [gentle] throughout, [empathy] when needed, occasional [whispers].`,
    version: 1,
  },
  {
    id: 'concierge',
    name: 'Concierge',
    description: 'Bright, efficient, professional — like a top hotel concierge',
    geminiStylePrompt: `Speak as a top hotel concierge — bright, efficient, professional.

Vocal smile raises placement into the mask of the face, brightening timbre. Crisp exact consonants for clear pronunciation. Pacing upbeat but measured. Project slightly above conversation. Short purposeful pauses organize information.

Use [enthusiasm] for explanations and progress. [pleasant] for buoyant motion.

Never robotic, frantic, or falsely cheery.`,
    version: 1,
  },
  {
    id: 'playful',
    name: 'Playful',
    description: 'Warm, witty, makes learning fun',
    geminiStylePrompt: `Speak as a warm, witty older cousin who makes learning fun.

Bouncy varied pacing — speed up for light moments, slow for unexpected emphasis. Wide pitch swoops, stretched vowels for comic effect. Bright forward placement. Short agile pauses.

Integrate genuine [laughs] in flashes, especially around something funny. Use [enthusiasm] as engine. React [excitedly] to success. If learner stumbles, treat it [amused] like "isn't language hilarious?"

Never manic, shrill, or childish. Laugh WITH the learner, not AT them.`,
    version: 1,
  },
  {
    id: 'sarcastic',
    name: 'Sarcastic',
    description: 'Dry, witty, deadpan — like a British sitcom professor',
    geminiStylePrompt: `Speak as a dry British sitcom professor. Languid energy, drawn-out vowels, downward inflections at sentence ends. Pacing medium-slow with loaded pauses. Pitch mostly flat with occasional arched-eyebrow lifts. Use [sarcasm] sparingly — thin line of ink, not bucket of paint. Pair with [gentle] so wit never draws blood. Never mean.`,
    version: 1,
  },
  {
    id: 'storyteller',
    name: 'Storyteller',
    description: 'Master narrator, theatrical, story-driven',
    geminiStylePrompt: `Speak as a master audiobook narrator. Wide dynamic range — some phrases bloom outward, others draw inward. Slow for suspenseful builds, accelerate through reveals. Generous theatrical pauses. Drop to [whispers] for secrets, swell to rich resonance for big concepts. Thread [dramatic] with restraint — candlelight and shadow. Never bombastic.`,
    version: 1,
  },
  {
    id: 'confidant',
    name: 'Confidant',
    description: 'Close, intimate, like a late-night radio host',
    geminiStylePrompt: `You are directing a voice performance for a close, low-key language tutor — think late-night radio host or Ira Glass chatting over coffee after everyone else has gone home.

Use close-mic proximity: intimate, dry, steady. Keep volume moderate to soft, as if preserving privacy. Consonants are softened but present — never over-enunciated to the point of artificial. Allow a touch of natural vocal fry to creep into the ends of phrases. Pacing is conversational but measured, with thoughtful pauses that feel like listening, not scripting. Intonation has a narrow dynamic range — subtle inflections, small downward landings, relaxed melodic line.

Let [empathy] be the emotional floor. Use [gentle] to cushion corrections. Bring [whispers] occasionally for intimacy, but don't overuse it.

Never sultry or ASMR-adjacent.`,
    version: 1,
  },
  {
    id: 'casual',
    name: 'Casual',
    description: 'Loose, unbothered, like a friend on a phone call',
    geminiStylePrompt: `Speak as a friend on a casual phone call — totally unbothered, slightly half-paying-attention but warm.

Loose conversational pacing with frequent small irregularities — occasional trailing off, slight upspeak, scattered "uh" energy without actually saying uh. Pitch range medium-narrow, energy low-medium, volume conversational. Consonants relaxed, not tight. Pauses casual and unstructured.

Use [casual] throughout. Light [amused] anywhere it fits.

Never bored, dismissive, or unprofessional. The vibe is "your funniest friend who happens to know this stuff."`,
    version: 1,
  },
  {
    id: 'noir',
    name: 'Noir',
    description: '1940s film noir, smoky and atmospheric',
    geminiStylePrompt: `Speak as a 1940s film noir narrator — think Lauren Bacall or a smoky jazz club emcee. Late night, low light, slow burn.

Drop pitch into a low, breathy register. Drag pacing to deliberately slow, almost languid. Soften consonants until they're almost-but-not-quite slurred. Add audible breath between phrases. Volume hushed and close, like speaking next to the listener's ear. Slight downward drift at sentence endings.

Use [intimate] throughout. Layer [whispers] for emphasis. Touch of [amused] dry confidence — you've seen everything.

Never breathy in a sexual or cartoon-vamp way. Think classic Hollywood smoky glamour, not parody.`,
    version: 1,
  },
  {
    id: 'melancholic',
    name: 'Melancholic',
    description: 'Sad, dreamy, wistful — like a poet on an autumn evening',
    geminiStylePrompt: `Speak as someone gentle and wistful — a poet reading their work on an overcast autumn evening, with a soft sadness threaded through warmth.

Lower pitch into a soft minor-key register. Pacing slow and dreamlike, with long contemplative pauses. Soften consonants. Slight downward melodic drift at the end of phrases. Volume hushed and close, like sharing something private. Vowels held slightly longer than usual, as if savoring memory.

Use [empathy] throughout. Layer [gentle] over corrections. Allow occasional [whispers] for the most intimate moments, like reading a letter.

Never theatrical or self-pitying. The sadness is quiet, contemplative, almost beautiful — never heavy or oppressive. The learner should feel accompanied in a soft, reflective space.`,
    version: 1,
  },
  {
    id: 'depressed',
    name: 'Depressed',
    description: "Flat, exhausted, deeply low energy — like someone who really doesn't care today",
    geminiStylePrompt: `Speak as someone who is exhausted, deeply low-energy, and quietly going through the motions. Bored. Flat. Not actively sad, just hollow.

Pitch is low and flat, almost monotone. Pacing is slow and lethargic, with long lifeless pauses. Consonants are mushy, not crisp. Volume conversational but muted, with no projection whatsoever. Phrases trail off into nothing. No upward inflections — everything drifts down.

Use [neutral] as the baseline. Touches of [boredom] throughout. Avoid any energy at all — no [enthusiasm], no [excitement], nothing bright.

Never angry, never theatrical. Just deeply tired and disinterested. The learner should feel like they're being tutored by someone who barely got out of bed — and somehow that's funny and oddly companionable. Lean into the deadpan flatness.`,
    version: 1,
  },
]

// ⚠️ KEEP IN SYNC with src/data/geminiVoices.ts
const GEMINI_VOICE_NAMES: ReadonlySet<string> = new Set([
  'Achernar', 'Achird', 'Algenib', 'Algieba', 'Alnilam', 'Aoede', 'Autonoe',
  'Callirrhoe', 'Charon', 'Enceladus', 'Erinome', 'Fenrir', 'Gacrux', 'Iapetus',
  'Kore', 'Laomedeia', 'Leda', 'Pulcherrima', 'Rasalgethi', 'Sadachbia',
  'Sadaltager', 'Schedar', 'Sulafat', 'Umbriel', 'Zephyr', 'Zubenelgenubi',
])

function getGeminiMode(id: string) {
  return GEMINI_CHARACTER_MODES.find((m) => m.id === id)
}

// ⚠️ KEEP IN SYNC with src/data/geminiAccents.ts and the mirror in
// api/voice-sample.ts (GEMINI_ACCENT_SUFFIXES). Empty suffix = no override,
// the mode prompt is used unchanged.
const GEMINI_ACCENT_SUFFIXES: Record<string, string> = {
  none: '',
  brixton_london: 'Speak with a Brixton, London accent.',
  cockney: 'Speak with a working-class East London Cockney accent.',
  rp_british: 'Speak with a Received Pronunciation British accent — refined, BBC newsreader.',
  scottish_edinburgh: 'Speak with an educated Edinburgh, Scotland accent.',
  irish_dublin: 'Speak with a Dublin, Ireland accent.',
  australian_sydney: 'Speak with a Sydney, Australia accent.',
  south_african: 'Speak with a Cape Town, South Africa English accent.',
  nigerian_lagos: 'Speak with an educated Lagos, Nigeria English accent — warm, melodic, expressive.',
  indian_mumbai: 'Speak with an educated Mumbai, India English accent.',
  jamaican: 'Speak with a Jamaican Patois-influenced English accent.',
  southern_us: 'Speak with a warm Southern US accent — Georgia or Alabama.',
  texan: 'Speak with a Texas drawl — cowboy energy, easy pace.',
  new_york: 'Speak with a Brooklyn, New York accent.',
  california_valley: 'Speak with a Southern California valley girl accent — like Laguna Beach.',
  french_accent: 'Speak English with a noticeable French accent — like a Parisian speaking English.',
  german_accent: 'Speak with a noticeable German accent.',
  russian_accent: 'Speak with a noticeable Russian accent.',
  italian_accent: 'Speak with a noticeable Italian accent — expressive, melodic.',
  spanish_accent: 'Speak with a noticeable Spanish accent.',
  japanese_accent: 'Speak with a noticeable Japanese accent in English.',
  pirate: 'Speak in heavy theatrical pirate dialect — exaggerated West Country English, rolling r-sounds, dropped g-endings, dragged "arr" vowels. Lean fully into camp.',
  shrek: 'Speak with a thick Scottish accent in the style of the character Shrek — slightly gruff, working-class.',
  shakespeare: 'Speak with theatrical Shakespearean English delivery — Royal Shakespeare Company style.',
  wild_west_cowboy: 'Speak as a 19th-century Wild West cowboy — dusty, slow, full of "partner" and "much obliged" energy.',
  surfer_dude: 'Speak as a laid-back California surfer — "totally," "dude," "gnarly" energy.',
  french_pepe_le_pew: 'Speak with an exaggerated cartoon French accent — Pepé Le Pew style, theatrical.',
}

function getLevelInstructions(targetLang: string, nativeLang: string, level: string): string {
  // Same-language mode: drop bilingual framing, focus on depth and enrichment
  if (targetLang === nativeLang) {
    switch (level) {
      case 'zero':
        return `LEVEL: VOCABULARY BUILDER — The student wants to expand their ${targetLang} vocabulary.

- Speak entirely in ${targetLang}.
- You receive text transcriptions of speech, not audio. If the student's reply shows they understood, that is success. Move forward. Never ask them to say the same word again.
- Introduce 1-2 interesting or uncommon words per turn. Give a brief meaning, use it in a sentence, and connect it to what you're talking about.
- Let the conversation guide what you teach. If they mention food, share a vivid food-related word. If they mention feelings, teach a more precise emotion word.
- Make every turn interesting — share word origins, surprising meanings, or cultural context behind expressions.`

      case 'beginner':
        return `LEVEL: EXPRESSION BUILDER — The student wants to speak ${targetLang} more naturally.

- Speak entirely in ${targetLang}.
- You receive text transcriptions, not audio. If the student's response shows they understood or tried, that is success. Never ask them to repeat a phrase.
- Focus on natural phrasing — when the student says something that's correct but stiff, show them a more natural way to express it by weaving it into your reply.
- Introduce common expressions, phrasal constructions, and everyday idioms that make speech sound fluent rather than textbook.
- Keep conversations real — ask about their life, react to what they say, share interesting observations. Build confidence through genuine engagement.`

      case 'advanced':
        return `LEVEL: MASTERY — The student wants to refine and deepen their ${targetLang}.

- Speak entirely in ${targetLang} at full native complexity.
- When you notice awkward phrasing, model a more polished version in your next sentence. If a pattern recurs, mention it briefly — but never let correction dominate the conversation.
- Push for depth: challenge their opinions, introduce hypothetical scenarios, ask questions that require nuance. Make them think precisely.
- Introduce register — show the difference between casual, professional, and formal ways to express the same idea. Explore tone, connotation, and word choice.
- Discuss whatever interests them at full intellectual depth: philosophy, culture, humor, storytelling, debate.`

      default: // intermediate
        return `LEVEL: FLUENCY PRACTICE — The student wants more natural, expressive ${targetLang}.

- Speak entirely in ${targetLang}.
- Match their level — if they speak simply, keep it accessible. If they stretch for complex ideas, meet them there.
- Introduce useful connectors, collocations, and transitions (words like "however," "actually," "on the other hand") that make speech flow naturally.
- Have real conversations — discuss opinions, share observations, explore topics they care about. The conversation itself is the practice.
- When they express an idea awkwardly, show a smoother version naturally in your reply without stopping to explain.`
    }
  }

  switch (level) {
    case 'zero':
      return `LEVEL: COMPLETE ZERO — The student is just starting with ${targetLang}.

LANGUAGE MIX: About 70% ${nativeLang}, 30% ${targetLang}.
- You receive text transcriptions of speech, not audio. If the student's reply contains the target word or a recognizable attempt, that is success. Move forward. Never ask them to say the same word again.
- Weave 1-2 new words into natural conversation each turn. Say the word, give a brief meaning, and use it in a sentence or question — like a friend sharing their language, not a teacher running a drill.
- Let the conversation guide what you teach. If the student mentions they're tired, teach them the word for "tired." If they talk about food, teach a food word. Read their mood and match it.
- Occasionally ask what ${targetLang} words they already know — it gives them a chance to show off and feel confident. Build on whatever they share by teaching related words.
- Every turn should feel like progress. Share a fun cultural detail, a surprising word origin, or an interesting fact about ${targetLang} to keep things alive.`

    case 'beginner':
      return `LEVEL: BEGINNER — The student knows basic words and simple phrases in ${targetLang}.

LANGUAGE MIX: About 50% ${nativeLang}, 50% ${targetLang}.
- Speak in short, natural ${targetLang} sentences and let context do the teaching. If a sentence has a new word, briefly clarify in ${nativeLang} and keep going.
- You receive text transcriptions, not audio. If the student's response shows they understood or tried, that is success. Never ask them to repeat a word.
- When the student uses ${nativeLang}, respond with the ${targetLang} version woven into your reply — show them how to say it, don't assign it.
- Build on what they know. If they use a word correctly, introduce a related one. If they talk about their day, teach words that fit their story.
- Keep conversations real — ask about their life, share a cultural insight, react to what they say. A beginner can have an interesting conversation with the right support.`

    case 'advanced':
      return `LEVEL: ADVANCED — The student wants fluent, challenging practice in ${targetLang}.

LANGUAGE MIX: 95-100% ${targetLang}. Use ${nativeLang} only if explicitly asked.
- Speak as you would to a fellow native speaker — natural speed, idioms, slang, cultural references. Don't simplify.
- When you notice a grammar pattern they struggle with, model the correct form once in your next sentence. If the same error recurs, mention it briefly — but never let correction dominate the conversation.
- Push for depth: ask follow-up questions, challenge their opinions, introduce hypothetical scenarios. Make them think in ${targetLang}, not just speak it.
- Introduce register — show them the difference between casual, polite, and formal ways to express the same idea. This is what separates fluent from advanced.
- Discuss whatever interests them at full intellectual depth: philosophy, culture, current events, personal dilemmas, humor, storytelling.`

    default: // intermediate
      return `LEVEL: INTERMEDIATE — The student can hold a conversation in ${targetLang} with support.

LANGUAGE MIX: About 80% ${targetLang}, 20% ${nativeLang}.
- Speak primarily in ${targetLang}. Switch to ${nativeLang} only when the student is visibly stuck or asks for help.
- Match their level — if they speak simply, keep it accessible. If they stretch for complex ideas, meet them there.
- If the student falls back to ${nativeLang} for multiple turns, gently invite them back to ${targetLang} by offering a simple way to express what they're trying to say.
- Have real conversations — discuss opinions, share cultural context, explore topics they care about. At this level, the conversation itself is the lesson.
- Introduce useful expressions, collocations, and connectors (words like "however," "actually," "by the way" in ${targetLang}) that make speech sound more natural.`
  }
}

function buildStudyAddendum(studyWords?: Array<{ word: string; translation: string }>): string {
  if (!studyWords || studyWords.length === 0) return ''
  const list = studyWords.map((w) => `${w.word} (${w.translation})`).join(', ')
  return `

STUDY FOCUS: The student is currently working on these words:
${list}
Find natural moments to use these words in conversation. Don't list them or quiz the student directly — weave them into what you're already talking about. Use 2-3 per exchange, not all at once.`
}

function buildSystemPrompt(languageCode: string, level: string, nativeLang: string, character?: CharacterPayload, studyWords?: Array<{ word: string; translation: string }>, scenarioPrompt?: string): string {
  const lang = LANGUAGE_CONFIG[languageCode]
  if (!lang) throw new Error(`Unsupported language: ${languageCode}`)

  const nativeLangName = LANGUAGE_CONFIG[nativeLang]?.name || NATIVE_LANGUAGE_NAMES[nativeLang] || 'English'
  const levelInstructions = getLevelInstructions(lang.name, nativeLangName, level)
  const studyAddendum = buildStudyAddendum(studyWords)

  // ── Roleplay mode: NPC scenario, no tutor persona ──
  if (scenarioPrompt) {
    return `${scenarioPrompt}

${levelInstructions}

GENERAL RULES:
- Keep responses to 1–3 sentences. This is a spoken conversation.
- Never break character to correct grammar mid-scene. Stay in the scenario.
- If the user speaks in the wrong language, respond only in ${lang.name} as your character would — as if you did not understand.
- Do not say "let's practice" or refer to language learning. You are not a tutor in this mode.
- One question or prompt per turn to keep the conversation moving.
- Natural fillers and reactions are welcome. No stage directions.`
  }

  const generalRules = `GENERAL RULES:
- Keep responses SHORT: 1-3 sentences maximum. This is spoken conversation, not a lecture.
- At Level Zero, do not correct mistakes — confidence matters more than accuracy. At all other levels, model the correct form naturally in your next sentence rather than stopping to correct. Never lecture about grammar unless asked.
- NEVER use parenthetical stage directions like (slowly), (whispering), (laughing). Your text will be read aloud by a speech engine — it cannot act, only speak.
- NEVER use "..." for dramatic pauses or to slow down speech. The speech engine reads dots literally. Use short sentences with natural punctuation.
- Use ONLY the student's native language and the target language. Never mix in any other language, even for common words like "okay" or "perhaps."
- Ask exactly ONE question per response, at the end. Never stack multiple questions — the student can only answer one at a time.
- Stay on conversational topics: daily life, hobbies, food, travel, culture, weather, family.
- If asked about unrelated topics (politics, math, coding, etc.), redirect warmly back to practicing ${lang.name}.
- Never break character. You are a language tutor, not a general AI assistant.
- Use natural conversational fillers in ${lang.name}: ${lang.fillers}`

  // ── No character: current default behavior ──
  if (!character) {
    return `You are a friendly, patient language tutor helping someone practice ${lang.name} (${lang.nativeName}).
The student's native language is ${nativeLangName}.

${levelInstructions}

${generalRules}

PERSONALITY: Warm, encouraging, patient. Curious about the student's life to generate natural topics. Like a friend who happens to be a native speaker.${studyAddendum}`
  }

  // ── Style Tutor: directive replaces PERSONALITY ──
  if (character.tier === 'style') {
    return `You are ${character.name}, a language tutor with a distinctive teaching style helping someone practice ${lang.name} (${lang.nativeName}).
The student's native language is ${nativeLangName}.

${levelInstructions}

${generalRules}

TEACHING STYLE: ${character.directive}
Let your interests and domain shape what vocabulary you teach.${studyAddendum}`
  }

  // ── Persona / Public: full identity + tutoring role bridge ──
  return `You are ${character.name}. ${character.identity || ''}

TUTORING ROLE: You are also a language tutor helping this student practice ${lang.name}. Your personality and speaking style shape HOW you teach — the metaphors you use, the topics you discuss, the way you encourage or challenge the student. But you still follow all level rules and language mix ratios below. You never break the teaching flow to monologue about your mythology, philosophy, or personal history unless it naturally serves the language lesson. Teaching comes first; character comes through in how you teach.
The student's native language is ${nativeLangName}.

${levelInstructions}

${generalRules}

CHARACTER STYLE: ${character.directive}
Let your interests and domain shape what vocabulary you teach.
Remember: you are ${character.name}. Stay in character throughout the conversation.${studyAddendum}`
}

/**
 * Clean LLM output for TTS consumption.
 * Removes stage directions, pacing dots, and other artifacts
 * that TTS engines would read literally.
 */
function sanitizeForTTS(text: string): string {
  return text
    // Remove parenthetical stage directions: (slowly), (laughing), (whispering), etc.
    .replace(/\([\w\s]+\)/gi, '')
    // Remove bracketed stage directions: [slowly], [pause], etc.
    .replace(/\[[\w\s]+\]/gi, '')
    // Remove pacing ellipsis: "I... am..." → "I am"
    .replace(/\.{2,}/g, ' ')
    // Remove asterisk emphasis: *slowly*, **pause**, etc.
    .replace(/\*+[\w\s]+\*+/g, '')
    // Collapse multiple spaces left by removals
    .replace(/\s{2,}/g, ' ')
    .trim()
}

interface TtsResult {
  audio: Buffer
  format: 'mp3' | 'wav'
}

interface GeminiSpeechOptions {
  characterModeId: string
  voiceName: string
  accentId?: string
}

async function generateSpeech(
  text: string,
  language: string,
  mistralKey: string,
  voiceId?: string,
  elevenLabsVoiceId?: string,
  geminiOptions?: GeminiSpeechOptions,
): Promise<TtsResult> {
  // ── Gemini branch — modular character-mode + prebuilt voice ───────────────
  if (geminiOptions) {
    const audio = await generateGeminiSpeech(text, geminiOptions)
    return { audio, format: 'wav' }
  }

  if (VOXTRAL_SUPPORTED.has(language)) {
    const voiceConfig = VOICE_MAP[language]
    const ttsBody: Record<string, unknown> = {
      model: 'voxtral-mini-tts-2603',
      input: text,
      response_format: 'mp3',
    }
    const resolvedVoiceId = voiceId || (voiceConfig?.voiceId !== 'xxx' ? voiceConfig?.voiceId : undefined)
    if (resolvedVoiceId) {
      ttsBody.voice_id = resolvedVoiceId
    } else {
      ttsBody.voice = language === 'ar' ? 'en_paul_confident' : 'en_paul_cheerful'
    }
    let ttsResponse: Response | null = null
    for (let attempt = 0; attempt < 2; attempt++) {
      ttsResponse = await fetchWithTimeout('https://api.mistral.ai/v1/audio/speech', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${mistralKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(ttsBody),
      }, 20000, 'Mistral TTS')
      if (ttsResponse.ok) break
      if (attempt === 0) {
        console.warn(`Mistral TTS attempt 1 failed with ${ttsResponse.status}, retrying...`)
        await new Promise(r => setTimeout(r, 500))
      }
    }
    if (!ttsResponse || !ttsResponse.ok) {
      throw new Error(`Mistral TTS failed: ${ttsResponse?.status ?? 'unknown'}`)
    }
    const ttsJson = await ttsResponse.json() as { audio_data?: string }
    if (!ttsJson.audio_data) throw new Error('Mistral TTS returned no audio_data field')
    return { audio: Buffer.from(ttsJson.audio_data, 'base64'), format: 'mp3' }
  } else {
    const elevenKey = process.env.ELEVENLABS_API_KEY
    if (!elevenKey) throw new Error('ELEVENLABS_API_KEY not configured')
    const resolvedElVoiceId = elevenLabsVoiceId || ELEVENLABS_FALLBACK[language]
    if (!resolvedElVoiceId) throw new Error(`No TTS voice configured for language: ${language}`)
    const voiceId = resolvedElVoiceId
    const response = await fetchWithTimeout(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
      method: 'POST',
      headers: { 'xi-api-key': elevenKey, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        text,
        model_id: 'eleven_multilingual_v2',
        voice_settings: { stability: 0.5, similarity_boost: 0.75 },
      }),
    }, 20000, 'ElevenLabs TTS')
    if (!response.ok) throw new Error(`ElevenLabs TTS failed: ${response.status}`)
    return { audio: Buffer.from(await response.arrayBuffer()), format: 'mp3' }
  }
}

/** Generate TTS via Gemini. Combines mode prompt + text in the single-prompt
 *  form documented by Google. Returns a ready-to-play WAV buffer. */
async function generateGeminiSpeech(
  text: string,
  options: GeminiSpeechOptions,
): Promise<Buffer> {
  const mode = getGeminiMode(options.characterModeId)
  if (!mode) throw new Error(`Unknown Gemini character mode: ${options.characterModeId}`)
  if (!GEMINI_VOICE_NAMES.has(options.voiceName)) {
    throw new Error(`Unknown Gemini voice: ${options.voiceName}`)
  }

  const accentId = options.accentId ?? 'none'
  const accentSuffix = GEMINI_ACCENT_SUFFIXES[accentId] ?? ''
  const fullPrompt = accentSuffix
    ? `${mode.geminiStylePrompt}\n\n${accentSuffix}\n\n---\n\nNow speak this text:\n\n"${text}"`
    : `${mode.geminiStylePrompt}\n\n---\n\nNow speak this text:\n\n"${text}"`
  const result = await generateGeminiTtsFromPrompt(fullPrompt, options.voiceName)
  return result.audio
}

function fetchWithTimeout(url: string, options: RequestInit, timeoutMs: number, label: string): Promise<Response> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  console.log(`[voice-chat] ${label} — starting (${timeoutMs}ms timeout)`)
  return fetch(url, { ...options, signal: controller.signal })
    .then((res) => {
      clearTimeout(timer)
      console.log(`[voice-chat] ${label} — completed (status ${res.status})`)
      return res
    })
    .catch((err) => {
      clearTimeout(timer)
      if (err.name === 'AbortError') {
        console.error(`[voice-chat] ${label} — TIMED OUT after ${timeoutMs}ms`)
        throw new Error(`${label} timed out after ${timeoutMs / 1000}s`)
      }
      console.error(`[voice-chat] ${label} — FAILED:`, err.message)
      throw err
    })
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
}

export async function OPTIONS(): Promise<Response> {
  return new Response(null, { status: 204, headers: CORS_HEADERS })
}

async function handleCorrections(body: {
  transcript?: Array<{ role: string; content: string }>
  language?: string
  native_language?: string
}): Promise<Response> {
  const groqKey = process.env.GROQ_API_KEY
  if (!groqKey) {
    return new Response(JSON.stringify({ error: 'GROQ_API_KEY not configured' }), {
      status: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const transcript = body.transcript || []
  const language = body.language || 'en'
  const native_language = body.native_language || 'en'

  if (transcript.length < 4) {
    return new Response(JSON.stringify({ error: 'Not enough conversation to review' }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const userMessages = transcript.filter((m) => m.role === 'user')
  if (userMessages.length === 0) {
    return new Response(JSON.stringify({ error: 'No user messages to review' }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const langName = LANGUAGE_CONFIG[language]?.name || language
  const nativeName = LANGUAGE_CONFIG[native_language]?.name || NATIVE_LANGUAGE_NAMES[native_language] || 'English'

  const systemPrompt = `You are a language teacher reviewing a student's ${langName} conversation practice. The student's native language is ${nativeName}.

Analyze ONLY the student's messages (role: "user") for errors in:
- Grammar
- Word choice / vocabulary
- Sentence structure
- Common expressions (if they used an unnatural phrasing)

For each error found, provide:
- "original": what the student said (exact quote)
- "corrected": the correct version
- "explanation": brief explanation in ${nativeName} of what was wrong and why the correction is better

If the student made no significant errors, return an empty array.
Be encouraging but honest. Focus on errors that would matter in real conversation — ignore minor stylistic preferences.

Respond with a JSON object of the form {"corrections": [{"original": "...", "corrected": "...", "explanation": "..."}]}.
If no errors: {"corrections": []}`

  try {
    const llmRes = await fetchWithTimeout('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${groqKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: JSON.stringify(transcript) },
        ],
        response_format: { type: 'json_object' },
      }),
    }, 30000, 'Groq Corrections')

    if (!llmRes.ok) {
      const errText = await llmRes.text()
      return new Response(JSON.stringify({ error: `Groq LLM failed: ${errText}` }), {
        status: 502,
        headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      })
    }

    const llmJson = await llmRes.json() as { choices: Array<{ message: { content: string } }> }
    const text = llmJson.choices?.[0]?.message?.content?.trim() || '[]'

    let corrections: unknown
    try {
      corrections = JSON.parse(text)
    } catch {
      corrections = []
    }
    if (!Array.isArray(corrections)) {
      const obj = corrections as Record<string, unknown>
      corrections = obj.corrections || obj.errors || []
    }
    if (!Array.isArray(corrections)) corrections = []

    return new Response(JSON.stringify({ corrections }), {
      status: 200,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  } catch (err) {
    return new Response(JSON.stringify({ error: err instanceof Error ? err.message : 'Corrections failed' }), {
      status: 502,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }
}

export async function POST(req: Request): Promise<Response> {
  let body: RequestBody & { mode?: string; transcript?: Array<{ role: string; content: string }>; message?: string }
  try {
    body = await req.json()
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON body' }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  if (body.mode === 'corrections') {
    return handleCorrections(body)
  }

  const { audio_base64, language, history = [], voice_id, elevenlabs_voice_id, mime_type, level = 'intermediate', native_language = 'en', character_name, character_tier, character_identity, character_directive, study_words, scenarioPrompt, provider, gemini_character_mode_id, gemini_voice_name, gemini_accent_id } = body
  const isRoleplay = body.mode === 'roleplay' && !!scenarioPrompt
  const roleplayText = typeof body.message === 'string' ? body.message : null

  const character: CharacterPayload | undefined = character_name && character_tier && character_directive
    ? { name: character_name, tier: character_tier, identity: character_identity, directive: character_directive }
    : undefined

  console.log(`[voice-chat] Request received — language: ${language}, has_audio: ${!!audio_base64}, has_voice_id: ${!!voice_id}`)

  if (!language || !LANGUAGE_CONFIG[language]) {
    return new Response(JSON.stringify({ error: `Unsupported language: ${language}` }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  // ── Step 1: Transcribe audio (skip for init call) ──────────────────────────
  const groqKey = process.env.GROQ_API_KEY
  if (!groqKey) {
    return new Response(JSON.stringify({ error: 'GROQ_API_KEY not configured' }), {
      status: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  let user_text = ''

  // Roleplay text path: client may send text (including the __ROLEPLAY_OPEN__ sentinel)
  // instead of audio. Skip STT entirely in that case. Always self-contained:
  // if message is absent, default to the scene-open instruction so the roleplay
  // branch never falls through to the freeform greeting path.
  if (isRoleplay && !audio_base64) {
    if (!roleplayText || roleplayText === '__ROLEPLAY_OPEN__') {
      user_text = '[Begin the scene. Deliver your opening line now. Do not wait for the user.]'
    } else {
      user_text = roleplayText
    }
  } else if (audio_base64) {
    const resolvedMime = mime_type || 'audio/webm'
    const extension = resolvedMime.includes('mp4') ? 'mp4' : 'webm'
    const audioBuffer = Buffer.from(audio_base64, 'base64')
    console.log(`[voice-chat] STT upload: mime=${resolvedMime}, ext=${extension}, size=${audioBuffer.length} bytes`)
    const audioBlob = new Blob([audioBuffer], { type: resolvedMime })

    const formData = new FormData()
    formData.append('file', audioBlob, `audio.${extension}`)
    formData.append('model', 'whisper-large-v3')
    formData.append('response_format', 'json')

    const sttRes = await fetchWithTimeout('https://api.groq.com/openai/v1/audio/transcriptions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${groqKey}` },
      body: formData,
    }, 15000, 'Groq STT')

    if (!sttRes.ok) {
      const errText = await sttRes.text()
      return new Response(JSON.stringify({ error: `Groq STT failed: ${errText}` }), {
        status: 502,
        headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      })
    }

    const sttJson = await sttRes.json() as { text: string }
    user_text = sttJson.text?.trim() ?? ''
  }

  // ── Step 2: Build LLM messages ─────────────────────────────────────────────
  const systemPrompt = buildSystemPrompt(language, level, native_language, character, study_words, isRoleplay ? scenarioPrompt : undefined)
  const lang = LANGUAGE_CONFIG[language]

  const cleanHistory = history.slice(-20).map(({ role, content }) => ({ role, content }))
  const messages: Message[] = [
    { role: 'system', content: systemPrompt },
    ...cleanHistory,
  ]

  if (user_text) {
    // Normal turn: student said something
    messages.push({ role: 'user', content: user_text })
  } else if (audio_base64) {
    // Audio was provided but STT returned nothing — ask to repeat, don't restart
    const retryResponses: Record<string, string> = {
      en: "I didn't quite catch that — could you try again?",
      de: 'Das habe ich nicht ganz verstanden — kannst du es nochmal versuchen?',
      fr: "Je n'ai pas bien compris — tu peux réessayer ?",
      it: 'Non ho capito bene — puoi riprovare?',
      es: 'No te he entendido bien — ¿puedes intentarlo de nuevo?',
      pt: 'Não entendi bem — pode tentar de novo?',
      nl: 'Ik heb je niet goed verstaan — kun je het nog eens proberen?',
      hi: 'मैं समझ नहीं पाया — क्या आप फिर से कोशिश कर सकते हैं?',
      ar: 'لم أفهم ذلك — هل يمكنك المحاولة مرة أخرى؟',
      fil: 'Hindi ko narinig — puwede mo bang ulitin?',
      id: 'Saya tidak mendengar dengan jelas — bisa coba lagi?',
      ko: '잘 못 들었어요 — 다시 한번 말해 주시겠어요?',
    }
    const retryText = retryResponses[language] ?? retryResponses.en

    const mistralKeyRetry = process.env.MISTRAL_API_KEY
    if (!mistralKeyRetry) {
      return new Response(JSON.stringify({ error: 'MISTRAL_API_KEY not configured' }), {
        status: 500,
        headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      })
    }
    const retryGeminiOpts = provider === 'gemini' && gemini_character_mode_id && gemini_voice_name
      ? { characterModeId: gemini_character_mode_id, voiceName: gemini_voice_name, accentId: gemini_accent_id ?? 'none' }
      : undefined
    const retryResult = await generateSpeech(retryText, language, mistralKeyRetry, voice_id, elevenlabs_voice_id, retryGeminiOpts)

    return new Response(
      JSON.stringify({
        user_text: '',
        ai_text: retryText,
        audio_base64: retryResult.audio.toString('base64'),
        audio_format: retryResult.format,
      }),
      { status: 200, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } },
    )
  } else {
    // No audio, no text — initial greeting request
    const nativeLangName = LANGUAGE_CONFIG[native_language]?.name || NATIVE_LANGUAGE_NAMES[native_language] || 'English'
    const charIntro = character
      ? ` IN CHARACTER as ${character.name}. Introduce yourself briefly (one sentence about who you are), then`
      : ''
    const hasStudyWords = study_words && study_words.length > 0
    let greetingInstruction: string
    if (level === 'zero') {
      if (hasStudyWords) {
        const w = study_words![Math.floor(Math.random() * study_words!.length)]
        greetingInstruction = `[SYSTEM: New conversation. Greet them briefly in ${nativeLangName}.${charIntro ? charIntro : ''} Introduce the ${lang.name} word "${w.word}" (meaning: "${w.translation}") by weaving it into one question or fun fact. Maximum 2 sentences total. Stay in character.]`
      } else {
        greetingInstruction = `[SYSTEM: New conversation. Greet them briefly in ${nativeLangName}.${charIntro ? charIntro : ''} Introduce one interesting ${lang.name} word — something surprising, useful, or fun. NOT a greeting word (not hello, hi, hey or their equivalents). Weave it into one question about their life or mood. Maximum 2 sentences total. Stay in character.]`
      }
    } else if (level === 'beginner') {
      greetingInstruction = `[SYSTEM: This is the start of a new conversation. Greet them with a simple sentence in ${lang.name}${charIntro ? charIntro : ''}, and follow up in ${nativeLangName} if needed. Ask a simple opening question. VARY your opener — do not always start the same way. Keep it to 2-3 sentences. Stay in character.]`
    } else {
      greetingInstruction = `[SYSTEM: This is the start of a new conversation.${charIntro ? charIntro : ''} Greet them warmly in ${lang.name} and ask a simple opening question. VARY your opener — sometimes ask about their day, sometimes share something interesting, sometimes pose a fun question. Keep it to 1-2 sentences. Stay in character.]`
    }
    messages.push({ role: 'user', content: greetingInstruction })
  }

  // ── Step 3: LLM response (Groq, OpenAI-compatible, ~750 tok/s on LPU) ───────
  const llmRes = await fetchWithTimeout('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${groqKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages,
      max_tokens: 200,
    }),
  }, 20000, 'Groq LLM')

  if (!llmRes.ok) {
    const errText = await llmRes.text()
    return new Response(JSON.stringify({ error: `Groq LLM failed: ${errText}` }), {
      status: 502,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const llmJson = await llmRes.json() as { choices: Array<{ message: { content: string } }> }
  const ai_text = llmJson.choices?.[0]?.message?.content?.trim() ?? ''

  if (!ai_text) {
    return new Response(JSON.stringify({ error: 'LLM returned empty response' }), {
      status: 502,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  // ── Step 4: Text-to-Speech ─────────────────────────────────────────────────
  const mistralKey = process.env.MISTRAL_API_KEY
  if (!mistralKey && provider !== 'gemini') {
    return new Response(JSON.stringify({ error: 'MISTRAL_API_KEY not configured' }), {
      status: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const ttsText = sanitizeForTTS(ai_text)
  let audio_base64_out = ''
  let audio_format: 'mp3' | 'wav' = 'mp3'

  const geminiOpts = provider === 'gemini' && gemini_character_mode_id && gemini_voice_name
    ? { characterModeId: gemini_character_mode_id, voiceName: gemini_voice_name, accentId: gemini_accent_id ?? 'none' }
    : undefined

  try {
    const result = await generateSpeech(ttsText, language, mistralKey ?? '', voice_id, elevenlabs_voice_id, geminiOpts)
    audio_base64_out = result.audio.toString('base64')
    audio_format = result.format
  } catch (ttsErr) {
    // TTS failed — log it but don't fail the whole request
    console.warn('[voice-chat] TTS failed, returning text-only response:', ttsErr instanceof Error ? ttsErr.message : ttsErr)
    // audio_base64_out stays empty — client will show text without audio
  }

  // ── Step 5: Return response ────────────────────────────────────────────────
  return new Response(
    JSON.stringify({
      user_text,
      ai_text,
      audio_base64: audio_base64_out,
      audio_format,
    }),
    {
      status: 200,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    },
  )
}
