import { generateGeminiTtsFromPrompt } from './_shared/geminiTts'
import {
  LANGUAGE_CONFIG,
  NATIVE_LANGUAGE_NAMES,
  resolveNativeLangName,
  type CharacterPayload,
} from './prompts/_shared/pedagogy'
import { buildVoxtralSystemPrompt, buildVoxtralGreeting } from './prompts/voxtral'
import { buildGeminiSystemPrompt, buildGeminiGreeting } from './prompts/gemini'
import { buildGenericSystemPrompt, buildGenericGreeting } from './prompts/_shared/generic'
import { corsHeaders, optionsResponse } from './_shared/cors'
import { ApiError, apiErrorResponse, errorResponse, jsonResponse, readJsonWithLimit, sanitizedProviderError } from './_shared/http'
import { requireSupabaseUser } from './_shared/auth'
import { consumeApiQuota } from './_shared/quota'
import {
  consumeFeatureAllowance,
  getFeatureUsed,
  recordFeatureUsage,
  refundFeatureUsage,
  resolveEntitlements,
  type UserEntitlements,
} from './_shared/entitlements'

// Audio-less turns (greeting, roleplay text) still spend LLM + TTS, so they
// debit a flat charge against the Speak allowance instead of slipping through
// unmetered (review finding 2026-07-28). 15s ≈ the provider cost of a typical
// spoken turn of that length.
const NO_AUDIO_TURN_BILLABLE_SECONDS = 15
import { writeUsageEvent } from './_shared/usageEvents'
import { analyticsPlatformFromRequest, trackServerCoreAction } from './_shared/analytics'
import {
  groqLlmCost, groqSttCost, geminiTtsCost, voxtralTtsCost,
  type LlmUsage, type GeminiTtsUsageLike,
} from './_shared/usageCost'

const SPEAK_LLM_MODEL = 'llama-3.3-70b-versatile'
const SPEAK_STT_MODEL = 'whisper-large-v3'
const SPEAK_GEMINI_TTS_MODEL = 'gemini-3.1-flash-tts-preview'
const SPEAK_VOXTRAL_TTS_MODEL = 'voxtral-mini-tts-2603'

// Vercel Serverless Function — Voice Tutor pipeline
// POST /api/voice-chat
// Body: { audio_base64: string|null, language: string, history: Message[], mime_type?: string }
// Returns: { user_text, ai_text, audio_base64, audio_format }
//
// Verified Gemini TTS response shape (live smoke test 2026-04-17 vs
// gemini-3.1-flash-tts-preview, mode=calm, voice=Aoede, en-intro sentence):
//   {
//     candidates: [{ content: { parts: [{ inlineData: {
//       mimeType: "audio/l16; rate=24000; channels=1",
//       data: "<base64 PCM16 mono 24kHz>"
//     } }] } }],
//     usageMetadata: { promptTokenCount, candidatesTokenCount, totalTokenCount, ... },
//     modelVersion, responseId
//   }
// PCM length for the 24-word intro sentence: 643,200 bytes (~13.4s audio).
// Wrap with wrapPcmAsWav() before returning to the client.

interface Message {
  role: 'user' | 'assistant' | 'system'
  content: string
}

interface RequestBody {
  audio_base64: string | null
  language: string
  history: Message[]
  voice_id?: string
  mime_type?: string
  level?: string
  native_language?: string
  character_name?: string
  character_tier?: 'style' | 'persona' | 'public'
  character_identity?: string
  character_directive?: string
  study_words?: Array<{ word: string; translation: string }>
  mode?: 'corrections' | 'roleplay'
  scenarioPrompt?: string
  provider?: 'voxtral' | 'gemini'
  gemini_character_mode_id?: string
  gemini_voice_name?: string
  gemini_accent_id?: string
  gemini_vibe_directive?: string
}

const VOICE_CHAT_BODY_MAX_BYTES = 6 * 1024 * 1024
const MAX_AUDIO_BASE64_LENGTH = 5_600_000
const MAX_DECODED_AUDIO_BYTES = 4 * 1024 * 1024
const MAX_HISTORY_ENTRIES = 20
const MAX_MESSAGE_LENGTH = 4_000
const MAX_TRANSCRIPT_ENTRIES = 40
const MAX_SCENARIO_PROMPT_LENGTH = 5_000
const MAX_CHARACTER_NAME_LENGTH = 120
const MAX_CHARACTER_FIELD_LENGTH = 2_000
const MAX_STUDY_WORDS = 20
const MAX_STUDY_WORD_FIELD_LENGTH = 160

// Mistral custom voice IDs — generated by scripts/generate-voices.ts
// Placeholder 'xxx' means: run the script, then paste actual voice_ids here.
// Until populated, falls back to preset voices (en_paul_cheerful / en_paul_confident).
const VOICE_MAP: Record<string, { voiceId: string; name: string; gender: string }> = {
  en: { voiceId: 'b20117b6-f11c-461f-9978-19968c237e32', name: 'Hope',     gender: 'female' },
  de: { voiceId: '5eea3a34-f977-4bbc-9a67-4050588ebc83', name: 'Mila',     gender: 'female' },
  fr: { voiceId: '99104b5b-e943-4598-878d-0a881a45baef', name: 'Claire',   gender: 'female' },
  it: { voiceId: '38647032-b1b5-4f8e-8ef6-04ac11925296', name: 'Elettra',  gender: 'female' },
  es: { voiceId: '20c4028f-ec23-47ae-af8a-fb2e0615abd8', name: 'Carolina', gender: 'female' },
  pt: { voiceId: '80d1df25-564a-47b6-9325-bb61277c8464', name: 'Yasmin',   gender: 'female' },
  nl: { voiceId: 'b6ed2ec1-bace-4d5e-88c2-ee1d881c115d', name: 'Melanie',  gender: 'female' },
  hi: { voiceId: '8dfc9345-ba80-4f88-91e8-92205ca53807', name: 'Kanika',   gender: 'female' },
  ar: { voiceId: '414a56c0-f4de-4ec1-8f8a-2bfffe963a1c', name: 'Yousef',   gender: 'male'   },
}

// Languages Voxtral TTS can speak. Any Speak language not in this set
// (fil, id, ko, ceb) is served by Gemini TTS instead — see generateSpeech().
const VOXTRAL_SUPPORTED = new Set(['en', 'de', 'fr', 'it', 'es', 'pt', 'nl', 'hi', 'ar'])

// Default Gemini character mode + voice used when a non-Voxtral language is
// requested without an explicit Gemini selection (e.g. the "Characters" path or
// roleplay for fil/id/ko/ceb). Keeps those languages audible via Gemini TTS.
const DEFAULT_GEMINI_OPTIONS: GeminiSpeechOptions = {
  characterModeId: 'concierge',
  voiceName: 'Kore',
  accentId: 'none',
}

// ⚠️ KEEP IN SYNC with src/data/geminiCharacterModes.ts
// If you edit a geminiStylePrompt, bump the `version` field here AND in the
// src/ twin, and UPDATE voice_samples SET invalidated_at = now() for that
// character_mode_id so cached samples regenerate.
const GEMINI_CHARACTER_MODES: ReadonlyArray<{
  id: string
  name: string
  description: string
  geminiStylePrompt: string
  version: number
}> = [
  {
    id: 'calm',
    name: 'Calm',
    description: 'Patient, slow-paced, encouraging meditation teacher',
    geminiStylePrompt: `Warm, slow, soft-volume meditation teacher. Lower pitch, softened consonants, generous pauses. [gentle] throughout, [empathy] when needed, occasional [whispers].`,
    version: 1,
  },
  {
    id: 'concierge',
    name: 'Concierge',
    description: 'Bright, efficient, professional — like a top hotel concierge',
    geminiStylePrompt: `Speak as a top hotel concierge — bright, efficient, professional.

Vocal smile raises placement into the mask of the face, brightening timbre. Crisp exact consonants for clear pronunciation. Pacing upbeat but measured. Project slightly above conversation. Short purposeful pauses organize information.

Use [enthusiasm] for explanations and progress. [pleasant] for buoyant motion.

Never robotic, frantic, or falsely cheery.`,
    version: 1,
  },
  {
    id: 'playful',
    name: 'Playful',
    description: 'Warm, witty, makes learning fun',
    geminiStylePrompt: `Speak as a warm, witty older cousin who makes learning fun.

Bouncy varied pacing — speed up for light moments, slow for unexpected emphasis. Wide pitch swoops, stretched vowels for comic effect. Bright forward placement. Short agile pauses.

Integrate genuine [laughs] in flashes, especially around something funny. Use [enthusiasm] as engine. React [excitedly] to success. If learner stumbles, treat it [amused] like "isn't language hilarious?"

Never manic, shrill, or childish. Laugh WITH the learner, not AT them.`,
    version: 1,
  },
  {
    id: 'sarcastic',
    name: 'Sarcastic',
    description: 'Dry, witty, deadpan — like a British sitcom professor',
    geminiStylePrompt: `Speak as a dry British sitcom professor. Languid energy, drawn-out vowels, downward inflections at sentence ends. Pacing medium-slow with loaded pauses. Pitch mostly flat with occasional arched-eyebrow lifts. Use [sarcasm] sparingly — thin line of ink, not bucket of paint. Pair with [gentle] so wit never draws blood. Never mean.`,
    version: 1,
  },
  {
    id: 'storyteller',
    name: 'Storyteller',
    description: 'Master narrator, theatrical, story-driven',
    geminiStylePrompt: `Speak as a master audiobook narrator. Wide dynamic range — some phrases bloom outward, others draw inward. Slow for suspenseful builds, accelerate through reveals. Generous theatrical pauses. Drop to [whispers] for secrets, swell to rich resonance for big concepts. Thread [dramatic] with restraint — candlelight and shadow. Never bombastic.`,
    version: 1,
  },
  {
    id: 'confidant',
    name: 'Confidant',
    description: 'Close, intimate, like a late-night radio host',
    geminiStylePrompt: `You are directing a voice performance for a close, low-key language tutor — think late-night radio host or Ira Glass chatting over coffee after everyone else has gone home.

Use close-mic proximity: intimate, dry, steady. Keep volume moderate to soft, as if preserving privacy. Consonants are softened but present — never over-enunciated to the point of artificial. Allow a touch of natural vocal fry to creep into the ends of phrases. Pacing is conversational but measured, with thoughtful pauses that feel like listening, not scripting. Intonation has a narrow dynamic range — subtle inflections, small downward landings, relaxed melodic line.

Let [empathy] be the emotional floor. Use [gentle] to cushion corrections. Bring [whispers] occasionally for intimacy, but don't overuse it.

Never sultry or ASMR-adjacent.`,
    version: 1,
  },
  {
    id: 'casual',
    name: 'Casual',
    description: 'Loose, unbothered, like a friend on a phone call',
    geminiStylePrompt: `Speak as a friend on a casual phone call — totally unbothered, slightly half-paying-attention but warm.

Loose conversational pacing with frequent small irregularities — occasional trailing off, slight upspeak, scattered "uh" energy without actually saying uh. Pitch range medium-narrow, energy low-medium, volume conversational. Consonants relaxed, not tight. Pauses casual and unstructured.

Use [casual] throughout. Light [amused] anywhere it fits.

Never bored, dismissive, or unprofessional. The vibe is "your funniest friend who happens to know this stuff."`,
    version: 1,
  },
  {
    id: 'noir',
    name: 'Noir',
    description: '1940s film noir, smoky and atmospheric',
    geminiStylePrompt: `Speak as a 1940s film noir narrator — think Lauren Bacall or a smoky jazz club emcee. Late night, low light, slow burn.

Drop pitch into a low, breathy register. Drag pacing to deliberately slow, almost languid. Soften consonants until they're almost-but-not-quite slurred. Add audible breath between phrases. Volume hushed and close, like speaking next to the listener's ear. Slight downward drift at sentence endings.

Use [intimate] throughout. Layer [whispers] for emphasis. Touch of [amused] dry confidence — you've seen everything.

Never breathy in a sexual or cartoon-vamp way. Think classic Hollywood smoky glamour, not parody.`,
    version: 1,
  },
  {
    id: 'melancholic',
    name: 'Melancholic',
    description: 'Sad, dreamy, wistful — like a poet on an autumn evening',
    geminiStylePrompt: `Speak as someone gentle and wistful — a poet reading their work on an overcast autumn evening, with a soft sadness threaded through warmth.

Lower pitch into a soft minor-key register. Pacing slow and dreamlike, with long contemplative pauses. Soften consonants. Slight downward melodic drift at the end of phrases. Volume hushed and close, like sharing something private. Vowels held slightly longer than usual, as if savoring memory.

Use [empathy] throughout. Layer [gentle] over corrections. Allow occasional [whispers] for the most intimate moments, like reading a letter.

Never theatrical or self-pitying. The sadness is quiet, contemplative, almost beautiful — never heavy or oppressive. The learner should feel accompanied in a soft, reflective space.`,
    version: 1,
  },
  {
    id: 'depressed',
    name: 'Depressed',
    description: "Flat, exhausted, deeply low energy — like someone who really doesn't care today",
    geminiStylePrompt: `Speak as someone who is exhausted, deeply low-energy, and quietly going through the motions. Bored. Flat. Not actively sad, just hollow.

Pitch is low and flat, almost monotone. Pacing is slow and lethargic, with long lifeless pauses. Consonants are mushy, not crisp. Volume conversational but muted, with no projection whatsoever. Phrases trail off into nothing. No upward inflections — everything drifts down.

Use [neutral] as the baseline. Touches of [boredom] throughout. Avoid any energy at all — no [enthusiasm], no [excitement], nothing bright.

Never angry, never theatrical. Just deeply tired and disinterested. The learner should feel like they're being tutored by someone who barely got out of bed — and somehow that's funny and oddly companionable. Lean into the deadpan flatness.`,
    version: 1,
  },
]

// ⚠️ KEEP IN SYNC with src/data/geminiVoices.ts
const GEMINI_VOICE_NAMES: ReadonlySet<string> = new Set([
  'Achernar', 'Achird', 'Algenib', 'Algieba', 'Alnilam', 'Aoede', 'Autonoe',
  'Callirrhoe', 'Charon', 'Enceladus', 'Erinome', 'Fenrir', 'Gacrux', 'Iapetus',
  'Kore', 'Laomedeia', 'Leda', 'Pulcherrima', 'Rasalgethi', 'Sadachbia',
  'Sadaltager', 'Schedar', 'Sulafat', 'Umbriel', 'Zephyr', 'Zubenelgenubi',
])

function getGeminiMode(id: string) {
  return GEMINI_CHARACTER_MODES.find((m) => m.id === id)
}

// ⚠️ KEEP IN SYNC with src/data/geminiAccents.ts and the mirror in
// api/voice-sample.ts (GEMINI_ACCENT_SUFFIXES). Empty suffix = no override,
// the mode prompt is used unchanged.
const GEMINI_ACCENT_SUFFIXES: Record<string, string> = {
  none: '',
  brixton_london: 'Speak with a Brixton, London accent.',
  cockney: 'Speak with a working-class East London Cockney accent.',
  rp_british: 'Speak with a Received Pronunciation British accent — refined, BBC newsreader.',
  scottish_edinburgh: 'Speak with an educated Edinburgh, Scotland accent.',
  irish_dublin: 'Speak with a Dublin, Ireland accent.',
  australian_sydney: 'Speak with a Sydney, Australia accent.',
  south_african: 'Speak with a Cape Town, South Africa English accent.',
  nigerian_lagos: 'Speak with an educated Lagos, Nigeria English accent — warm, melodic, expressive.',
  indian_mumbai: 'Speak with an educated Mumbai, India English accent.',
  jamaican: 'Speak with a Jamaican Patois-influenced English accent.',
  southern_us: 'Speak with a warm Southern US accent — Georgia or Alabama.',
  texan: 'Speak with a Texas drawl — cowboy energy, easy pace.',
  new_york: 'Speak with a Brooklyn, New York accent.',
  california_valley: 'Speak with a Southern California valley girl accent — like Laguna Beach.',
  french_accent: 'Speak English with a noticeable French accent — like a Parisian speaking English.',
  german_accent: 'Speak with a noticeable German accent.',
  russian_accent: 'Speak with a noticeable Russian accent.',
  italian_accent: 'Speak with a noticeable Italian accent — expressive, melodic.',
  spanish_accent: 'Speak with a noticeable Spanish accent.',
  japanese_accent: 'Speak with a noticeable Japanese accent in English.',
  pirate: 'Speak in heavy theatrical pirate dialect — exaggerated West Country English, rolling r-sounds, dropped g-endings, dragged "arr" vowels. Lean fully into camp.',
  shrek: 'Speak with a thick Scottish accent in the style of the character Shrek — slightly gruff, working-class.',
  shakespeare: 'Speak with theatrical Shakespearean English delivery — Royal Shakespeare Company style.',
  wild_west_cowboy: 'Speak as a 19th-century Wild West cowboy — dusty, slow, full of "partner" and "much obliged" energy.',
  surfer_dude: 'Speak as a laid-back California surfer — "totally," "dude," "gnarly" energy.',
  french_pepe_le_pew: 'Speak with an exaggerated cartoon French accent — Pepé Le Pew style, theatrical.',
}

// ────────────────────────────────────────────────────────────────────────────
// Provider-specific prompt construction lives in api/prompts/{voxtral,gemini,
// _shared/generic}.ts. Routing (see POST handler) is inference-based —
// matches current dispatch: Gemini requires gemini_vibe_directive + no
// character; Voxtral requires character; else Generic. The frontend only sets
// body.provider for Gemini today, so explicit provider === 'voxtral' would
// miss Voxtral traffic entirely.
// ────────────────────────────────────────────────────────────────────────────

/**
 * Clean LLM output for TTS consumption.
 * Removes stage directions, pacing dots, and other artifacts
 * that TTS engines would read literally.
 */
function sanitizeForTTS(text: string): string {
  return text
    // Remove parenthetical stage directions: (slowly), (laughing), (whispering), etc.
    .replace(/\([\w\s]+\)/gi, '')
    // Remove bracketed stage directions: [slowly], [pause], etc.
    .replace(/\[[\w\s]+\]/gi, '')
    // Remove pacing ellipsis: "I... am..." → "I am"
    .replace(/\.{2,}/g, ' ')
    // Remove asterisk emphasis: *slowly*, **pause**, etc.
    .replace(/\*+[\w\s]+\*+/g, '')
    // Collapse multiple spaces left by removals
    .replace(/\s{2,}/g, ' ')
    .trim()
}

interface TtsResult {
  audio: Buffer
  format: 'mp3' | 'wav'
  provider: 'gemini' | 'voxtral'
  model: string
  usage?: GeminiTtsUsageLike   // Gemini TTS token usage (text in + audio out)
  chars?: number               // Voxtral synthesized character count
}

interface GeminiSpeechOptions {
  characterModeId: string
  voiceName: string
  accentId?: string
}

/** Estimate TTS spend from a TtsResult (Gemini audio/text tokens or Voxtral chars). */
function ttsCostOf(result: TtsResult): number {
  return result.provider === 'gemini' ? geminiTtsCost(result.usage) : voxtralTtsCost(result.chars)
}

function buildGeminiTtsPrompt(
  text: string,
  language: string,
  modePrompt: string,
  accentSuffix: string,
): string {
  const lang = LANGUAGE_CONFIG[language]
  const languageLabel = lang ? `${lang.name} (${language})` : language

  return [
    '# PERFORMANCE DIRECTIONS',
    modePrompt,
    accentSuffix ? `\n${accentSuffix}` : '',
    '',
    '# OUTPUT RULES',
    'Read only the transcript inside the <transcript> tags.',
    'Read the transcript exactly as written.',
    `The transcript language is ${languageLabel}. Keep every word in that language.`,
    'Do not translate, paraphrase, summarize, answer, or add commentary.',
    'Do not substitute English words or words from any other language.',
    'If accent or style directions conflict with the transcript language, preserve the transcript language and treat the accent only as a light delivery color.',
    '',
    '<transcript>',
    text,
    '</transcript>',
  ].filter(Boolean).join('\n')
}

async function generateSpeech(
  text: string,
  language: string,
  mistralKey: string,
  voiceId?: string,
  geminiOptions?: GeminiSpeechOptions,
): Promise<TtsResult> {
  // ── Gemini branch — modular character-mode + prebuilt voice ───────────────
  if (geminiOptions) {
    const { audio, usage } = await generateGeminiSpeech(text, language, geminiOptions)
    return { audio, format: 'wav', provider: 'gemini', model: SPEAK_GEMINI_TTS_MODEL, usage }
  }

  if (VOXTRAL_SUPPORTED.has(language)) {
    const voiceConfig = VOICE_MAP[language]
    const ttsBody: Record<string, unknown> = {
      model: 'voxtral-mini-tts-2603',
      input: text,
      response_format: 'mp3',
    }
    const resolvedVoiceId = voiceId || (voiceConfig?.voiceId !== 'xxx' ? voiceConfig?.voiceId : undefined)
    if (resolvedVoiceId) {
      ttsBody.voice_id = resolvedVoiceId
    } else {
      ttsBody.voice = language === 'ar' ? 'en_paul_confident' : 'en_paul_cheerful'
    }
    let ttsResponse: Response | null = null
    for (let attempt = 0; attempt < 2; attempt++) {
      ttsResponse = await fetchWithTimeout('https://api.mistral.ai/v1/audio/speech', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${mistralKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(ttsBody),
      }, 20000, 'Mistral TTS')
      if (ttsResponse.ok) break
      if (attempt === 0) {
        console.warn(`Mistral TTS attempt 1 failed with ${ttsResponse.status}, retrying...`)
        await new Promise(r => setTimeout(r, 500))
      }
    }
    if (!ttsResponse || !ttsResponse.ok) {
      throw new Error(`Mistral TTS failed: ${ttsResponse?.status ?? 'unknown'}`)
    }
    const ttsJson = await ttsResponse.json() as { audio_data?: string }
    if (!ttsJson.audio_data) throw new Error('Mistral TTS returned no audio_data field')
    return {
      audio: Buffer.from(ttsJson.audio_data, 'base64'), format: 'mp3',
      provider: 'voxtral', model: SPEAK_VOXTRAL_TTS_MODEL, chars: text.length,
    }
  } else {
    // Non-Voxtral language (fil, id, ko, ceb) with no explicit Gemini pick —
    // serve it with Gemini TTS using a sensible default mode + voice.
    const { audio, usage } = await generateGeminiSpeech(text, language, DEFAULT_GEMINI_OPTIONS)
    return { audio, format: 'wav', provider: 'gemini', model: SPEAK_GEMINI_TTS_MODEL, usage }
  }
}

/** Generate TTS via Gemini. Combines mode prompt + text in the single-prompt
 *  form documented by Google. Returns a ready-to-play WAV buffer. */
async function generateGeminiSpeech(
  text: string,
  language: string,
  options: GeminiSpeechOptions,
): Promise<{ audio: Buffer; usage: GeminiTtsUsageLike }> {
  const mode = getGeminiMode(options.characterModeId)
  if (!mode) throw new Error(`Unknown Gemini character mode: ${options.characterModeId}`)
  if (!GEMINI_VOICE_NAMES.has(options.voiceName)) {
    throw new Error(`Unknown Gemini voice: ${options.voiceName}`)
  }

  const accentId = options.accentId ?? 'none'
  const accentSuffix = GEMINI_ACCENT_SUFFIXES[accentId] ?? ''
  const fullPrompt = buildGeminiTtsPrompt(text, language, mode.geminiStylePrompt, accentSuffix)
  const result = await generateGeminiTtsFromPrompt(fullPrompt, options.voiceName)
  return { audio: result.audio, usage: result.usage }
}

function fetchWithTimeout(url: string, options: RequestInit, timeoutMs: number, label: string): Promise<Response> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  console.log(`[voice-chat] ${label} — starting (${timeoutMs}ms timeout)`)
  return fetch(url, { ...options, signal: controller.signal })
    .then((res) => {
      clearTimeout(timer)
      console.log(`[voice-chat] ${label} — completed (status ${res.status})`)
      return res
    })
    .catch((err) => {
      clearTimeout(timer)
      if (err.name === 'AbortError') {
        console.error(`[voice-chat] ${label} — TIMED OUT after ${timeoutMs}ms`)
        throw new Error(`${label} timed out after ${timeoutMs / 1000}s`)
      }
      console.error(`[voice-chat] ${label} — FAILED:`, err.message)
      throw err
    })
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function readString(value: unknown, field: string, maxLength: number, required = false): string | undefined {
  if (value === undefined || value === null) {
    if (required) throw new ApiError(400, `${field} is required`)
    return undefined
  }
  if (typeof value !== 'string') throw new ApiError(400, `${field} must be a string`)
  const trimmed = value.trim()
  if (required && !trimmed) throw new ApiError(400, `${field} is required`)
  if (trimmed.length > maxLength) throw new ApiError(400, `${field} is too long`)
  return trimmed
}

function validateLanguageKey(value: unknown, field: string, allowNativeNames = false): string {
  const language = readString(value, field, 32, true)!
  if (!LANGUAGE_CONFIG[language] && !(allowNativeNames && NATIVE_LANGUAGE_NAMES[language])) {
    throw new ApiError(400, `Unsupported ${field}`)
  }
  return language
}

function decodedBase64Length(value: string): number {
  if (!/^[A-Za-z0-9+/]*={0,2}$/.test(value) || value.length % 4 !== 0) {
    throw new ApiError(400, 'audio_base64 is malformed')
  }
  const padding = value.endsWith('==') ? 2 : value.endsWith('=') ? 1 : 0
  return (value.length / 4) * 3 - padding
}

function validateMessages(value: unknown, field: string, maxEntries: number): Message[] {
  if (value === undefined || value === null) return []
  if (!Array.isArray(value)) throw new ApiError(400, `${field} must be an array`)
  if (value.length > maxEntries) throw new ApiError(413, `${field} is too large`)
  return value.map((entry, index) => {
    if (!isObject(entry)) throw new ApiError(400, `${field}[${index}] is invalid`)
    const role = entry.role
    // The system prompt is server-authored; a client-supplied 'system' entry
    // would be spliced straight into the LLM context (audit 2026-09-03 A-06).
    if (role !== 'user' && role !== 'assistant') {
      throw new ApiError(400, `${field}[${index}].role is invalid`)
    }
    const content = readString(entry.content, `${field}[${index}].content`, MAX_MESSAGE_LENGTH, true)!
    return { role, content }
  })
}

function validateStudyWords(value: unknown): Array<{ word: string; translation: string }> | undefined {
  if (value === undefined || value === null) return undefined
  if (!Array.isArray(value)) throw new ApiError(400, 'study_words must be an array')
  if (value.length > MAX_STUDY_WORDS) throw new ApiError(400, 'study_words has too many entries')
  return value.map((entry, index) => {
    if (!isObject(entry)) throw new ApiError(400, `study_words[${index}] is invalid`)
    return {
      word: readString(entry.word, `study_words[${index}].word`, MAX_STUDY_WORD_FIELD_LENGTH, true)!,
      translation: readString(entry.translation, `study_words[${index}].translation`, MAX_STUDY_WORD_FIELD_LENGTH, true)!,
    }
  })
}

function validateVoiceBody(raw: unknown): RequestBody & {
  transcript?: Array<{ role: string; content: string }>
  message?: string
} {
  if (!isObject(raw)) throw new ApiError(400, 'Request body must be an object')

  const mode = raw.mode
  if (mode !== undefined && mode !== 'corrections' && mode !== 'roleplay') {
    throw new ApiError(400, 'mode is invalid')
  }

  const provider = raw.provider
  if (provider !== undefined && provider !== 'voxtral' && provider !== 'gemini') {
    throw new ApiError(400, 'provider is invalid')
  }

  const language = validateLanguageKey(raw.language, 'language')
  const nativeLanguage = raw.native_language === undefined
    ? undefined
    : validateLanguageKey(raw.native_language, 'native_language', true)

  const audioValue = raw.audio_base64
  let audioBase64: string | null = null
  if (audioValue !== undefined && audioValue !== null) {
    audioBase64 = readString(audioValue, 'audio_base64', MAX_AUDIO_BASE64_LENGTH, false) ?? null
    if (audioBase64) {
      const decodedLength = decodedBase64Length(audioBase64)
      if (decodedLength > MAX_DECODED_AUDIO_BYTES) {
        throw new ApiError(413, 'audio_base64 is too large')
      }
    }
  }

  const transcript = raw.transcript === undefined
    ? undefined
    : validateMessages(raw.transcript, 'transcript', MAX_TRANSCRIPT_ENTRIES)
  if (mode === 'corrections' && transcript && transcript.length < 4) {
    throw new ApiError(400, 'Not enough conversation to review')
  }

  const characterTier = raw.character_tier
  if (characterTier !== undefined && characterTier !== 'style' && characterTier !== 'persona' && characterTier !== 'public') {
    throw new ApiError(400, 'character_tier is invalid')
  }

  return {
    audio_base64: audioBase64,
    language,
    history: validateMessages(raw.history, 'history', MAX_HISTORY_ENTRIES),
    voice_id: readString(raw.voice_id, 'voice_id', 128),
    mime_type: readString(raw.mime_type, 'mime_type', 128),
    level: readString(raw.level, 'level', 64),
    native_language: nativeLanguage,
    character_name: readString(raw.character_name, 'character_name', MAX_CHARACTER_NAME_LENGTH),
    character_tier: characterTier as RequestBody['character_tier'],
    character_identity: readString(raw.character_identity, 'character_identity', MAX_CHARACTER_FIELD_LENGTH),
    character_directive: readString(raw.character_directive, 'character_directive', MAX_CHARACTER_FIELD_LENGTH),
    study_words: validateStudyWords(raw.study_words),
    mode: mode as RequestBody['mode'],
    scenarioPrompt: readString(raw.scenarioPrompt, 'scenarioPrompt', MAX_SCENARIO_PROMPT_LENGTH),
    provider: provider as RequestBody['provider'],
    gemini_character_mode_id: readString(raw.gemini_character_mode_id, 'gemini_character_mode_id', 128),
    gemini_voice_name: readString(raw.gemini_voice_name, 'gemini_voice_name', 128),
    gemini_accent_id: readString(raw.gemini_accent_id, 'gemini_accent_id', 128),
    gemini_vibe_directive: readString(raw.gemini_vibe_directive, 'gemini_vibe_directive', MAX_CHARACTER_FIELD_LENGTH),
    transcript,
    message: readString(raw.message, 'message', MAX_MESSAGE_LENGTH),
  }
}

export async function OPTIONS(req?: Request): Promise<Response> {
  return optionsResponse(req)
}

async function handleCorrections(body: {
  transcript?: Array<{ role: string; content: string }>
  language?: string
  native_language?: string
}, req: Request): Promise<Response> {
  const groqKey = process.env.GROQ_API_KEY
  if (!groqKey) {
    return errorResponse(req, 500, 'Voice service is not configured')
  }

  const transcript = body.transcript || []
  const language = body.language || 'en'
  const native_language = body.native_language || 'en'

  if (transcript.length < 4) {
    return errorResponse(req, 400, 'Not enough conversation to review')
  }

  const userMessages = transcript.filter((m) => m.role === 'user')
  if (userMessages.length === 0) {
    return errorResponse(req, 400, 'No user messages to review')
  }

  const langName = LANGUAGE_CONFIG[language]?.name || language
  const nativeName = LANGUAGE_CONFIG[native_language]?.name || NATIVE_LANGUAGE_NAMES[native_language] || 'English'

  const systemPrompt = `You are a language teacher reviewing a student's ${langName} conversation practice. The student's native language is ${nativeName}.

Analyze ONLY the student's messages (role: "user") for errors in:
- Grammar
- Word choice / vocabulary
- Sentence structure
- Common expressions (if they used an unnatural phrasing)

For each error found, provide:
- "original": what the student said (exact quote)
- "corrected": the correct version
- "explanation": brief explanation in ${nativeName} of what was wrong and why the correction is better

If the student made no significant errors, return an empty array.
Be encouraging but honest. Focus on errors that would matter in real conversation — ignore minor stylistic preferences.

Respond with a JSON object of the form {"corrections": [{"original": "...", "corrected": "...", "explanation": "..."}]}.
If no errors: {"corrections": []}`

  try {
    const llmRes = await fetchWithTimeout('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${groqKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: JSON.stringify(transcript) },
        ],
        response_format: { type: 'json_object' },
      }),
    }, 30000, 'Groq Corrections')

    if (!llmRes.ok) {
      return sanitizedProviderError(req, 'Corrections service unavailable')
    }

    const llmJson = await llmRes.json() as { choices: Array<{ message: { content: string } }> }
    const text = llmJson.choices?.[0]?.message?.content?.trim() || '[]'

    let corrections: unknown
    try {
      corrections = JSON.parse(text)
    } catch {
      corrections = []
    }
    if (!Array.isArray(corrections)) {
      const obj = corrections as Record<string, unknown>
      corrections = obj.corrections || obj.errors || []
    }
    if (!Array.isArray(corrections)) corrections = []

    return jsonResponse(req, { corrections }, 200)
  } catch (err) {
    console.error('[voice-chat] Corrections failed:', err instanceof Error ? err.message : err)
    return sanitizedProviderError(req, 'Corrections service unavailable')
  }
}

export async function POST(req: Request): Promise<Response> {
  let body: RequestBody & { mode?: string; transcript?: Array<{ role: string; content: string }>; message?: string }
  let userId = ''
  let entitlements: UserEntitlements | null = null
  let speakSecondsUsedBefore = 0
  // Seconds debited for this turn (set after STT). A turn the user never
  // received (LLM failure) gives them back — otherwise a provider outage
  // silently burns the free trial (audit 2026-09-03 F-05). TTS failures
  // degrade to text and are correctly not refunded.
  let debitedSpeakSeconds = 0
  const refundSpeakDebit = async () => {
    if (debitedSpeakSeconds > 0 && entitlements && !entitlements.isAdmin) {
      await refundFeatureUsage(userId, 'speak_seconds', entitlements.periodKey, debitedSpeakSeconds)
      debitedSpeakSeconds = 0
    }
  }
  try {
    const user = await requireSupabaseUser(req)
    userId = user.id
    const rawBody = await readJsonWithLimit<unknown>(req, VOICE_CHAT_BODY_MAX_BYTES)
    body = validateVoiceBody(rawBody)
    // Provider config is checked before any quota or allowance is spent (A-12).
    if (!process.env.GROQ_API_KEY) {
      throw new ApiError(503, 'Voice service is not configured')
    }
    await consumeApiQuota(user.id, 'voice_chat')

    // Speak-minute allowance (free: lifetime trial; paid: per-period grant).
    // Corrections mode is a post-session text review — never gated, so a learner
    // who ran out mid-conversation can still collect their feedback.
    if (body.mode !== 'corrections') {
      entitlements = await resolveEntitlements(user.id)
      if (!entitlements.isAdmin) {
        speakSecondsUsedBefore = await getFeatureUsed(user.id, 'speak_seconds', entitlements.periodKey)
        if (speakSecondsUsedBefore >= entitlements.grants.speakSeconds) {
          throw new ApiError(403, 'Speak allowance is used up', {
            code: entitlements.plan === 'free' ? 'speak_trial_exhausted' : 'speak_allowance_exhausted',
            plan: entitlements.plan,
            used_seconds: Math.round(speakSecondsUsedBefore),
            limit_seconds: entitlements.grants.speakSeconds,
          })
        }
      }
    }
  } catch (err) {
    if (err instanceof ApiError) return apiErrorResponse(req, err)
    console.error('[voice-chat] Request gate failed:', err instanceof Error ? err.message : err)
    return errorResponse(req, 400, 'Invalid request')
  }

  if (body.mode === 'corrections') {
    return handleCorrections(body, req)
  }

  try {
  const { audio_base64, language, history = [], voice_id, mime_type, level = 'intermediate', native_language = 'en', character_name, character_tier, character_identity, character_directive, study_words, scenarioPrompt, provider, gemini_character_mode_id, gemini_voice_name, gemini_accent_id, gemini_vibe_directive } = body
  const isRoleplay = body.mode === 'roleplay' && !!scenarioPrompt
  const roleplayText = typeof body.message === 'string' ? body.message : null

  const character: CharacterPayload | undefined = character_name && character_tier && character_directive
    ? { name: character_name, tier: character_tier, identity: character_identity, directive: character_directive }
    : undefined

  console.log(`[voice-chat] Request received — language: ${language}, has_audio: ${!!audio_base64}, has_voice_id: ${!!voice_id}`)

  if (!language || !LANGUAGE_CONFIG[language]) {
    return errorResponse(req, 400, `Unsupported language: ${language}`)
  }

  // ── Step 1: Transcribe audio (skip for init call) ──────────────────────────
  const groqKey = process.env.GROQ_API_KEY
  if (!groqKey) {
    return errorResponse(req, 500, 'Voice service is not configured')
  }

  let user_text = ''
  // Usage accumulators for the per-turn pipeline_events row (written at the end).
  const turnStartedAt = Date.now()
  let sttDurationSeconds: number | null = null
  let llmUsage: LlmUsage | undefined

  // Roleplay text path: client may send text (including the __ROLEPLAY_OPEN__ sentinel)
  // instead of audio. Skip STT entirely in that case. Always self-contained:
  // if message is absent, default to the scene-open instruction so the roleplay
  // branch never falls through to the freeform greeting path.
  if (isRoleplay && !audio_base64) {
    if (!roleplayText || roleplayText === '__ROLEPLAY_OPEN__') {
      user_text = '[Begin the scene. Deliver your opening line now. Do not wait for the user.]'
    } else {
      user_text = roleplayText
    }
  } else if (audio_base64) {
    const resolvedMime = mime_type || 'audio/webm'
    const extension = resolvedMime.includes('mp4') ? 'mp4' : 'webm'
    const audioBuffer = Buffer.from(audio_base64, 'base64')
    console.log(`[voice-chat] STT upload: mime=${resolvedMime}, ext=${extension}, size=${audioBuffer.length} bytes`)
    const audioBlob = new Blob([audioBuffer], { type: resolvedMime })

    const formData = new FormData()
    formData.append('file', audioBlob, `audio.${extension}`)
    formData.append('model', 'whisper-large-v3')
    // verbose_json returns the real audio `duration` (for cost metering) alongside `text`.
    formData.append('response_format', 'verbose_json')

    const sttRes = await fetchWithTimeout('https://api.groq.com/openai/v1/audio/transcriptions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${groqKey}` },
      body: formData,
    }, 15000, 'Groq STT')

    if (!sttRes.ok) {
      return sanitizedProviderError(req, 'Speech transcription service unavailable')
    }

    const sttJson = await sttRes.json() as { text?: string; duration?: number }
    user_text = sttJson.text?.trim() ?? ''
    if (typeof sttJson.duration === 'number') sttDurationSeconds = sttJson.duration
  }

  // ── Step 1b: Debit the Speak allowance atomically, BEFORE LLM/TTS spend ────
  // Ceiling = allowance + this turn, so a turn that starts with remaining > 0
  // may cross the boundary once, but concurrent or oversized turns cannot run
  // away (the next request is denied by ceiling and pre-check alike).
  const billableSeconds = sttDurationSeconds && sttDurationSeconds > 0
    ? sttDurationSeconds
    : NO_AUDIO_TURN_BILLABLE_SECONDS
  let speakSecondsUsedAfter: number | null = null
  if (entitlements) {
    if (entitlements.isAdmin) {
      await recordFeatureUsage(userId, 'speak_seconds', entitlements.periodKey, billableSeconds)
    } else {
      const debit = await consumeFeatureAllowance(
        userId,
        'speak_seconds',
        entitlements.periodKey,
        billableSeconds,
        entitlements.grants.speakSeconds + billableSeconds,
      )
      if (!debit.allowed) {
        return apiErrorResponse(req, new ApiError(403, 'Speak allowance is used up', {
          code: entitlements.plan === 'free' ? 'speak_trial_exhausted' : 'speak_allowance_exhausted',
          plan: entitlements.plan,
          used_seconds: Math.round(debit.used),
          limit_seconds: entitlements.grants.speakSeconds,
        }))
      }
      speakSecondsUsedAfter = debit.used
      debitedSpeakSeconds = billableSeconds
    }
  }

  // ── Step 2: Build LLM messages ─────────────────────────────────────────────
  const effectiveScenario = isRoleplay ? scenarioPrompt : undefined
  let systemPrompt: string
  if (!character && gemini_vibe_directive) {
    systemPrompt = buildGeminiSystemPrompt({
      language,
      level,
      nativeLanguage: native_language,
      studyWords: study_words,
      vibeDirective: gemini_vibe_directive,
      scenarioPrompt: effectiveScenario,
    })
  } else if (character) {
    systemPrompt = buildVoxtralSystemPrompt({
      language,
      level,
      nativeLanguage: native_language,
      character,
      studyWords: study_words,
      scenarioPrompt: effectiveScenario,
    })
  } else {
    systemPrompt = buildGenericSystemPrompt({
      language,
      level,
      nativeLanguage: native_language,
      studyWords: study_words,
      scenarioPrompt: effectiveScenario,
    })
  }
  const lang = LANGUAGE_CONFIG[language]

  const cleanHistory = history.slice(-20).map(({ role, content }) => ({ role, content }))
  const messages: Message[] = [
    { role: 'system', content: systemPrompt },
    ...cleanHistory,
  ]

  if (user_text) {
    // Normal turn: student said something
    messages.push({ role: 'user', content: user_text })
  } else if (audio_base64) {
    // Audio was provided but STT returned nothing — ask to repeat, don't restart
    const retryResponses: Record<string, string> = {
      en: "I didn't quite catch that — could you try again?",
      de: 'Das habe ich nicht ganz verstanden — kannst du es nochmal versuchen?',
      fr: "Je n'ai pas bien compris — tu peux réessayer ?",
      it: 'Non ho capito bene — puoi riprovare?',
      es: 'No te he entendido bien — ¿puedes intentarlo de nuevo?',
      pt: 'Não entendi bem — pode tentar de novo?',
      nl: 'Ik heb je niet goed verstaan — kun je het nog eens proberen?',
      hi: 'मैं समझ नहीं पाया — क्या आप फिर से कोशिश कर सकते हैं?',
      ar: 'لم أفهم ذلك — هل يمكنك المحاولة مرة أخرى؟',
      fil: 'Hindi ko narinig — puwede mo bang ulitin?',
      id: 'Saya tidak mendengar dengan jelas — bisa coba lagi?',
      ko: '잘 못 들었어요 — 다시 한번 말해 주시겠어요?',
      ceb: 'Wala ko kadungog — puwede ba nimo usbon?',
      ru: 'Что-то плохо слышно — повтори, пожалуйста?',
    }
    const retryText = retryResponses[language] ?? retryResponses.en

    const retryGeminiOpts = provider === 'gemini' && gemini_character_mode_id && gemini_voice_name
      ? { characterModeId: gemini_character_mode_id, voiceName: gemini_voice_name, accentId: gemini_accent_id ?? 'none' }
      : undefined
    const mistralKeyRetry = process.env.MISTRAL_API_KEY
    if (!mistralKeyRetry && !retryGeminiOpts && VOXTRAL_SUPPORTED.has(language)) {
      return errorResponse(req, 500, 'Voice service is not configured')
    }
    const retryResult = await generateSpeech(retryText, language, mistralKeyRetry ?? '', voice_id, retryGeminiOpts)

    // STT ran (and was billed) but returned nothing — record the STT + retry-TTS spend.
    const retrySttCost = groqSttCost(sttDurationSeconds)
    const retryTtsCost = ttsCostOf(retryResult)
    await writeUsageEvent({
      // STT (groq) + TTS (voxtral/gemini) blend — model_provider 'multi' so the
      // per-provider rollup isn't falsely credited to one vendor; the per-component
      // split lives in metadata.
      userId, feature: 'speak_turn', stage: 'speak', status: 'partial',
      modelProvider: 'multi', modelName: null,
      costUsd: retrySttCost + retryTtsCost,
      audioSeconds: sttDurationSeconds, chars: retryResult.chars ?? null,
      latencyMs: Date.now() - turnStartedAt, errorType: 'stt_empty',
      metadata: {
        language, mode: 'stt_retry',
        stt: { provider: 'groq', model: SPEAK_STT_MODEL, audio_seconds: sttDurationSeconds, cost_usd: retrySttCost },
        tts: { provider: retryResult.provider, model: retryResult.model, chars: retryResult.chars ?? null, usage: retryResult.usage ?? null, cost_usd: retryTtsCost },
      },
    })

    return new Response(
      JSON.stringify({
        user_text: '',
        ai_text: retryText,
        audio_base64: retryResult.audio.toString('base64'),
        audio_format: retryResult.format,
      }),
      { status: 200, headers: { ...corsHeaders(req), 'Content-Type': 'application/json' } },
    )
  } else {
    // No audio, no text — initial greeting request
    const nativeLangName = resolveNativeLangName(native_language)
    const studyWord = study_words && study_words.length > 0
      ? study_words[Math.floor(Math.random() * study_words.length)]
      : null
    let greetingInstruction: string
    if (character) {
      greetingInstruction = buildVoxtralGreeting({
        level,
        targetLangName: lang.name,
        nativeLangName,
        character,
        studyWord,
      })
    } else if (gemini_vibe_directive) {
      greetingInstruction = buildGeminiGreeting({
        level,
        targetLangName: lang.name,
        nativeLangName,
        studyWord,
      })
    } else {
      greetingInstruction = buildGenericGreeting({
        level,
        targetLangName: lang.name,
        nativeLangName,
        studyWord,
      })
    }
    messages.push({ role: 'user', content: greetingInstruction })
  }

  const isGreeting = !user_text && !audio_base64

  // ── Step 3: LLM response (Groq, OpenAI-compatible, ~750 tok/s on LPU) ───────
  const llmRes = await fetchWithTimeout('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${groqKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages,
      max_tokens: 200,
      // Greetings use a deliberately minimal prompt; raise temperature so the
      // LLM explores more varied openers instead of locking onto one phrasing
      // across every call. Non-greeting turns keep the Groq default.
      ...(isGreeting ? { temperature: 1.0 } : {}),
    }),
  }, 20000, 'Groq LLM')

  if (!llmRes.ok) {
    // LLM call failed (not billed); STT may already have been billed this turn.
    await writeUsageEvent({
      userId, feature: 'speak_turn', stage: 'speak', status: 'failed',
      modelProvider: 'groq', modelName: SPEAK_LLM_MODEL,
      costUsd: groqSttCost(sttDurationSeconds), audioSeconds: sttDurationSeconds,
      latencyMs: Date.now() - turnStartedAt, errorType: `llm_http_${llmRes.status}`,
      metadata: { language, stt: { provider: 'groq', model: SPEAK_STT_MODEL, audio_seconds: sttDurationSeconds } },
    })
    await refundSpeakDebit()
    return sanitizedProviderError(req, 'Voice chat service unavailable')
  }

  const llmJson = await llmRes.json() as { choices: Array<{ message: { content: string } }>; usage?: LlmUsage }
  if (llmJson.usage) llmUsage = llmJson.usage
  const ai_text = llmJson.choices?.[0]?.message?.content?.trim() ?? ''

  if (!ai_text) {
    // LLM returned (and was billed) but produced no text — record STT + LLM spend.
    const emptyLlm = groqLlmCost(SPEAK_LLM_MODEL, llmUsage)
    await writeUsageEvent({
      userId, feature: 'speak_turn', stage: 'speak', status: 'failed',
      modelProvider: 'groq', modelName: SPEAK_LLM_MODEL,
      costUsd: groqSttCost(sttDurationSeconds) + emptyLlm.costUsd,
      tokensIn: emptyLlm.tokensIn, tokensOut: emptyLlm.tokensOut,
      audioSeconds: sttDurationSeconds, latencyMs: Date.now() - turnStartedAt,
      errorType: 'empty_ai_text',
      metadata: { language, stt: { provider: 'groq', model: SPEAK_STT_MODEL, audio_seconds: sttDurationSeconds } },
    })
    await refundSpeakDebit()
    return sanitizedProviderError(req, 'Voice chat service unavailable')
  }

  // ── Step 4: Text-to-Speech ─────────────────────────────────────────────────
  const geminiOpts = provider === 'gemini' && gemini_character_mode_id && gemini_voice_name
    ? { characterModeId: gemini_character_mode_id, voiceName: gemini_voice_name, accentId: gemini_accent_id ?? 'none' }
    : undefined

  // Mistral is only required when we'll actually call Voxtral (a Voxtral-supported
  // language with no Gemini selection). Gemini-served turns need GOOGLE_AI_API_KEY.
  const mistralKey = process.env.MISTRAL_API_KEY
  if (!mistralKey && !geminiOpts && VOXTRAL_SUPPORTED.has(language)) {
    return errorResponse(req, 500, 'Voice service is not configured')
  }

  const ttsText = sanitizeForTTS(ai_text)
  let audio_base64_out = ''
  let audio_format: 'mp3' | 'wav' = 'mp3'
  let ttsResult: TtsResult | null = null
  let ttsFailed = false

  try {
    ttsResult = await generateSpeech(ttsText, language, mistralKey ?? '', voice_id, geminiOpts)
    audio_base64_out = ttsResult.audio.toString('base64')
    audio_format = ttsResult.format
  } catch (ttsErr) {
    // TTS failed — log it but don't fail the whole request
    ttsFailed = true
    console.warn('[voice-chat] TTS failed, returning text-only response:', ttsErr instanceof Error ? ttsErr.message : ttsErr)
    // audio_base64_out stays empty — client will show text without audio
  }

  // ── Step 5: Record per-turn usage + cost — one pipeline_events row per turn ──
  const sttCost = groqSttCost(sttDurationSeconds)
  const llm = groqLlmCost(SPEAK_LLM_MODEL, llmUsage)
  const ttsCost = ttsResult ? ttsCostOf(ttsResult) : 0
  await writeUsageEvent({
    // STT (groq) + LLM (groq) + TTS (voxtral/gemini) blend — model_provider 'multi'
    // so the per-provider rollup isn't falsely credited to Groq; the per-component
    // split (incl. each provider + model) lives in metadata.
    userId, feature: 'speak_turn', stage: 'speak',
    status: ttsFailed ? 'partial' : 'success',
    modelProvider: 'multi', modelName: null,
    costUsd: sttCost + llm.costUsd + ttsCost,
    tokensIn: llm.tokensIn, tokensOut: llm.tokensOut,
    audioSeconds: sttDurationSeconds,
    chars: ttsResult?.chars ?? null,
    latencyMs: Date.now() - turnStartedAt,
    errorType: ttsFailed ? 'tts_failed' : null,
    metadata: {
      language,
      mode: isRoleplay ? 'roleplay' : (isGreeting ? 'greeting' : 'turn'),
      stt: { provider: 'groq', model: SPEAK_STT_MODEL, audio_seconds: sttDurationSeconds, cost_usd: sttCost },
      llm: { provider: 'groq', model: SPEAK_LLM_MODEL, tokens_in: llm.tokensIn, tokens_out: llm.tokensOut, cost_usd: llm.costUsd },
      tts: ttsResult
        ? { provider: ttsResult.provider, model: ttsResult.model, chars: ttsResult.chars ?? null, usage: ttsResult.usage ?? null, cost_usd: ttsCost }
        : { failed: true },
    },
  })

  // Portfolio learning_action: one core_action per completed speak turn (the
  // pipeline_events row above stays the detailed cost ledger).
  if (userId) {
    await trackServerCoreAction({
      userId,
      platform: analyticsPlatformFromRequest(req),
      kind: 'speak_turn',
      props: {
        duration_s: sttDurationSeconds,
        compute: {
          tokens_in: llm.tokensIn,
          tokens_out: llm.tokensOut,
          est_cost_usd: sttCost + llm.costUsd + ttsCost,
          providers: ttsResult ? ['groq', ttsResult.provider] : ['groq'],
        },
      },
    })
  }

  // The allowance was debited in Step 1b (atomic, pre-LLM/TTS).
  const speakAllowance = entitlements && !entitlements.isAdmin
    ? {
        plan: entitlements.plan,
        limit_seconds: entitlements.grants.speakSeconds,
        remaining_seconds: Math.max(
          0,
          Math.round(entitlements.grants.speakSeconds - (speakSecondsUsedAfter ?? speakSecondsUsedBefore + billableSeconds)),
        ),
      }
    : null

  // ── Step 6: Return response ────────────────────────────────────────────────
  return new Response(
    JSON.stringify({
      user_text,
      ai_text,
      audio_base64: audio_base64_out,
      audio_format,
      speak_allowance: speakAllowance,
    }),
    {
      status: 200,
      headers: { ...corsHeaders(req), 'Content-Type': 'application/json' },
    },
  )
  } catch (err) {
    console.error('[voice-chat] Provider flow failed:', err instanceof Error ? err.message : err)
    await refundSpeakDebit()
    return sanitizedProviderError(req, 'Voice chat service unavailable')
  }
}
